### ISSUE TITLE
Handle trailing thrown exceptions better

### ISSUE THREAD

**Issue by mwpowellhtx** [catchorg/Catch2#1058]
What do I mean by that? I have destructors in which potentially error conditions can cause exceptions. Maybe a good thing or not; style aside, when they are allocated using smart pointers, which go out of scope with the test cases and/or sections, the program crashes ungracefully rather than Catch presenting a pretty response.

I don't know if that could be handled better, maybe a parent try/catch scope around the test case(s), or something like that?

It's not impossible to workaround, but it would be nice to catch it better.

Thanks!

**Comment by philsquared** [comment]
There *is* a parent try/catch around the call into the test case. It *should* be handling it gracefully.
If it's crashing it suggests that there's an exception being thrown during stack unwind due to another exception (an easy situation to get into with throwing destructors, and why they're not usually recommended - although I sometimes find them useful, too).

Is this in the case where the test case is concluding successfully, or has a test failed and it's exiting early (assertions starting with `REQUIRE` exit by throwing an exception!)

**Comment by mwpowellhtx** [comment]
Yes, that's precisely what I'm talking about. Can a parent-parent scope be added to buffer for this situation?

Like I said, it's when the resource is cleaned up at stack unwind. Smart pointer resets itself, dtor encounters exception.

**Comment by mwpowellhtx** [comment]
One workaround, I suppose I could introduce a superfluous parent SECTION. However, I'm really trying to stay focused just on the unit tests I want to perform without the superfluity, if you will.

**Comment by horenmar** [comment]
>Yes, that's precisely what I'm talking about. Can a parent-parent scope be added to buffer for this situation?

No, because ultimately the error happens when an exception is thrown while a different one is in-flight.

Consider this example
```cpp
struct throws {
    ~throws() {
        throw 1;
    }
};

void safish() {
    throws a;
}

void always_aborts() {
    throws a, b;
}
```
Function `safish` can be called and the program's stack will unwind in standard fashion. Thus this
```cpp
try {
    safish();
} catch (int) {
}
```
is an absolutely pointless piece of code, but harmless. On the other hand, calling `always_aborts()` will instantly kill your program, because C++ standard specifies that if a second exception is thrown while the first one is in-flight, `std::terminate` is called immediately.

This is the reason why exceptions inside destructor are regarded as a bad idea. However, there are legitimate reasons to use them, but they have to be used smartly, ie the following version of the `throws` struct would allow calling `always_aborts` without immediate termination of the program.
```cpp
struct throws {
    ~throws() {
        if (!std::uncaught_exception()) {
            throw 1;
        }
    }
};
```
