### ISSUE TITLE
Can't find Catch::rngSeed anymore in Catch2

### ISSUE THREAD

**Issue by Morwenn** [catchorg/Catch2#1076]
## Description

My CI just broke tonight because it can't apparently find `Catch::rngSeed()` anymore. Wherever I used it, I've now got the following error with MinGW-w64 g++7.1:

    error: 'rngSeed' is not a member of 'Catch'

It seems weird considering that the function seems to remain in the source.

### Steps to reproduce

Just try to compile anything with `Catch::rngSeed()`.

### Extra information

It's also worth nothing that the header `internal/catch_random_number_generator.h` even though it looks harmless. It doesn't seem to be causing the problem.

* Catch version: **v2.0.1**
* Operating System: **Ubuntu & Windows**
* Compiler+version: **MinGW-w64 g++ 7.1, g++5, clang++3.8**

**Comment by horenmar** [comment]
I want to say that this is why you shouldn't clone ToT of dependency, but that is not really helpful. The crux of the issue is that at some point `rngSeed` was no longer dependency of Catch's main interface, and so the stitching script moved it into non-interface part of Catch. This means that it is only provided in the file that defines `CATCH_CONFIG_RUNNER` or `CATCH_CONFIG_MAIN`.

I will have to check if we promised `Catch::rngSeed` as a part of our external interface, if yes we will move it back. In the meantime, you can work around the issue by calling `Catch::getCurrentContext().getConfig()->rngSeed()`.

**Comment by Morwenn** [comment]
Ok, I will work around it for now, thanks :)

**Comment by Morwenn** [comment]
sssss

**Comment by horenmar** [comment]
Sorry, I expected context to be part of what we leak to the outside world.

Anyway, we will try to establish more firm external API in the future (`rngSeed` will likely end up being part of it).

**Comment by Morwenn** [comment]
Nice, thanks for considering it!
