### ISSUE TITLE
Slow compiling and "undefined reference to 'vtable for CLASS_NAME'" error

### ISSUE THREAD

**Issue by diablol1** [catchorg/Catch2#1081]
I tried these things
1. https://github.com/catchorg/Catch2/blob/master/docs/slow-compiles.md#top
2. Making own main function

But I'm still getting "undefined reference to 'vtable for ClassName'" and "undefined reference to `ClassName:Function" errors when testing my own classes and it's compiling very slowly for every type
* Catch version: **v2.0.1**
* Operating System: **Windows 7**
* Compiler+version: **Mingw w64 5.0**

**Comment by horenmar** [comment]
We are going to need more details. What file are you trying to compile? How do you invoke the compiler? etc

**Comment by diablol1** [comment]
I'm using cmake. Here's [Project.zip](https://github.com/catchorg/Catch2/files/1443919/Project.zip) on which I was trying to compile test and errors  https://pastebin.com/3nur6Y0U

**Comment by horenmar** [comment]
Can you provide smaller example? I don't have an easy access to any system where I can compile things including `<any>`.

**Comment by diablol1** [comment]
Compiling speed is normal now, even though I didn't change anything. Here's similar [Project.zip](https://github.com/catchorg/Catch2/files/1444138/Project.zip)

**Comment by horenmar** [comment]
@diablol1 If you don't object I am going to call this resolved then.

**Comment by diablol1** [comment]
But this error still occurs

**Comment by horenmar** [comment]
Sorry, I thought it resolved itself because of the last post.

Anyway, I downloaded the second provided project and found two problems:
1) `InitCatch.hpp` is a header file and thus isn't compiled. After I renamed it to `InitCatch.cpp` so it is compiled, it compiles except for 2 undefined references to the SampleClass methods.
2) The `Tests` project does not link against other files, so implementations of `SampleClass::setVar(int)` and `SampleClass::getVar()` aren't linked in. When I provided their definitions in the test files (to keep it simpler), the test linked properly.

Does this resolve your problem?

**Comment by diablol1** [comment]
Yes, thanks, but "Linking CXX executable Tests.exe" lasts almost 2 minutes. [Project.zip](https://github.com/catchorg/Catch2/files/1461815/Project.zip)

**Comment by diablol1** [comment]
I figured it out. This takes about 2 minutes of linking when using gcc from Msys, but works great with Mingw

**Comment by horenmar** [comment]
So, should this be considered resolved?

**Comment by diablol1** [comment]
Yes
