### ISSUE TITLE
Catch v2.0.1 - CHECK(-0.0019569472 == Approx(0.0).epsilon(0.1)); does not work

### ISSUE THREAD

**Issue by mariusz102102** [catchorg/Catch2#1096]
## Description
Regression v2.0.1 compare  v1.9.7

### Steps to reproduce
    TEST_CASE("Test weight")
    {
        CHECK(-0.0019569472 == Approx(0.0).epsilon(0.1));
    }

```
g:\test\test.cpp(91): FAILED:
  CHECK( -0.0019569472 == Approx(0.0).epsilon(0.1) )
with expansion:
  -0.0019569472 == Approx( 0.0 )
```

### Extra information
Below test case fails on v2.0.1 passed in catch v1.9.7
* Catch version: **v2.0.1**
* Operating System: *Windows 10 **
* Compiler+version: **Visual studio 15.4**

**Comment by horenmar** [comment]
This is actually an intended change, called out in the "breaking changes" part of the v2.0.1 release.

We removed default up-scaling of epsilon (the relative margin allowed) because it silently gave bad results for lowish numbers: ie, it accepted the above comparison even though `-0.001` and `0.0` are not within 10% of each other.

**Comment by hoisunng** [comment]
In my test cases I sometimes even have the case that 1e-20 != Approx(0).
So after this change, what is the suggested way of writing in Catch2, if we want to assert that something is approximately zero?

**Comment by horenmar** [comment]
Depends on how close to zero you want to be, but for comparisons close to zero the recommended way is
`value == Approx(0).margin(allowable_margin)`.
