### ISSUE TITLE
Possibly corollary to Command Line Arguments access

### ISSUE THREAD

**Issue by mwpowellhtx** [catchorg/Catch2#1132]
This is a possible follow on to [Access command line arguments from test cases](890) to do with accessing Command Line Arguments.

First of all, I use the Catch-provided Main, for starters. Maybe this still allows for arguments access from within a Test Case, I don't know? Preferably with Catch-provided Main, but either way, if I need to cook up my own custom command line arguments map friendly Main, that's acceptable as well...

I want to pass custom command line arguments into my Test Cases for diagnostic purposes, help direct Test Cases one way or another, that sort of thing. Such as, ``--swerve-left 1`` or ``--swerve-right 1``, that sort of thing.

Possible? If not currently, doable?

**Comment by philsquared** [comment]
Since #890 was closed Catch2 has been released with the new version of Clara that is built from the ground up to be composable.
This allows you to add your own custom arguments easily (although you'll still need to provide your own way of getting them into test cases, e.g. using globals or singletons).

See: https://github.com/catchorg/Catch2/blob/master/docs/own-main.md#adding-your-own-command-line-options

**Comment by mwpowellhtx** [comment]
Great, thank you!
