### ISSUE TITLE
Usage of deprecated std::uncaught_exception

### ISSUE THREAD

**Issue by Hedanito** [catchorg/Catch2#1137]
## Description
The latest version of visual studio (15.5.2) started marking deprecated functions and produces warnings when they are used. One of these is `std::uncaught_exception`, which is used by Catch. Support for `std::uncaught_exceptions` should be detected and used instead when available.

### Steps to reproduce
 * Get Visual Studio 15.5.2
 * Enable the latest C++ features using the `_HAS_CXX17=1` macro and the `/std:c++latest` compiler flag
 * Now you will receive a warning whenever you use `std::uncaught_exception`

Warning example:
```
2>C:\Users\rick_\.conan\data\Catch\2.0.1\aurion\stable\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\catch/catch.hpp(7196): warning C4996: 'std::uncaught_exception': warning STL4006: std::uncaught_exception() is deprecated in C++17. It is superseded by std::uncaught_exceptions(), plural. You can define _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\exception(17): note: see declaration of 'std::uncaught_exception'
```

### Extra information
* Catch version: **v2.0.1**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 15.5.2**

**Comment by BMBurstein** [comment]
This has been "fixed" (the warning is ignored) in the source, but not yet in the generated single header. Maybe this should be closed?

**Comment by philsquared** [comment]
I've marked it for closure after the next release (should be soon - winding up again after the holidays :-) )

**Comment by horenmar** [comment]
Yeah, the warning is ignored because the proper fix is to use C++17, but we intend to stay at C++11 for some time. In the meantime, the worst it will do is that a `SECTION` created while an exception is in-flight will think it ended up early and message macros used while an exception is in-flight will be always reported. Neither of these seem overly problematic (the first is mostly academical, the second is reasonable).

Anyway, v2.1.0 is out with the fix.
