### ISSUE TITLE
Proposal: Dataproviders

### ISSUE THREAD

**Issue by ThirtySomething** [catchorg/Catch2#1177]
Please excuse my contribution if this is the wrong place.

I have used Catch in some projects, but I haven't had much experience with it. Sometimes it seemed a bit awkward to me, for example when I wanted to run a test with several different values. 

In PHPUnit there is the concept of [data providers](https://phpunit.readthedocs.io/en/latest/writing-tests-for-phpunit.html?highlight=dataprovider#data-providers). Is something similar possible for Catch? Or did I not understand a part of Catch correctly? Then I'm grateful for tips.

**Comment by horenmar** [comment]
Catch Classic used to implement generators, but they were never documented or officially supported because the old implementation did not work together with sections.

We have an aggregation issue for this request, #850, and it is definitely on the map, but it has to work properly with sections before it is included in Catch2.

**Comment by ThirtySomething** [comment]
Oh, I didn't know about the generators in the first version of Catch. Thanks for the reference to #850. If it suits you, I'll close this issue - as you note it in there. I fully understand the decision to implement the generators only with C++11 or even C++14. I have worked on a larger project in the past and could not use C++11. This has made things more complicated and difficult.
