### ISSUE TITLE
Catch2 Session.run(argc, argv) is no longer const char*

### ISSUE THREAD

**Issue by bdb** [catchorg/Catch2#1178]
v1.x used const char*, v2 uses char*. I didn't see this change mentioned anywhere, and searching the issues did not yield anything easy to find. I could see wanting to support both types, but not removing const char* for char*.

Edit: Catch1 was actually 'const char* const argv[]'. And v2 is just 'char* argv[]' 

Makes it a pain converting from Catch1.

Catch version: v2.1.1

**Comment by horenmar** [comment]
The underlying reason for change is that Clara (the CLI parsing library) moved to use `char* argv[]` for its argument handling. This was done because only two signatures are fully compliant according to the standard: `int main(void)` and `int main(int argc, char* argv[])` (see #615).

Also note that `char**` isn't convertible to `const char**`, but we are thinking about providing a `const char * const * argv` overload.

**Comment by bdb** [comment]
Thanks for the update. It would be nice to provide the const overload as it's quite common, but I've changed our tests.
