### ISSUE TITLE
Access violations cause crashes

### ISSUE THREAD

**Issue by davidaue** [catchorg/Catch2#1212]
## Description
Access violations (or probably any SEH) cause Catch to crash. From native code the reporter tries to access a null object. From managed code the reporter goes haywire.

### Steps to reproduce
See attached project
[CatchSEH.zip](https://github.com/catchorg/Catch2/files/1790333/CatchSEH.zip)

### Extra information
* Catch version: **v2.2.**
* Operating System: **Win 10*
* Compiler+version: **VS 2017**

**Comment by horenmar** [comment]
Finally got around testing this and, after I played with the project and google around a bit, I think the sanest solution is to just stop supporting SEH for C++/CLI code.

**Comment by davidaue** [comment]
I see the same problem in fully native C++ projects.

[CatchSEHNative.zip](https://github.com/catchorg/Catch2/files/1866654/CatchSEHNative.zip)

**Comment by horenmar** [comment]
After more messing around, there is indeed a potential bug in the base class for streaming reporters, but it is fairly harmless. The bug is that after `StreamingReporterBase::testRunEnded` is called, some stored information is thrown away, and if it is accessed, it will lead to dereferencing a `nullptr`. Doing this should not be necessary, as the destructor should clear those data members anyway and it would prevent this kind of mistakes.

However, a call to `IStreamingReporter::testRunEnded` should only happen when the test run is over, and our internal logic prevents this from happening during standard operation. There are 2 ways it can happen anyway:

* Triggering structured exceptions under debugger. For some reason, if the structured exception reaches debugger's handler, then it is told to resume at the position. This means that under debugger, this code will forever loop on the second line
```cpp
	int* p = nullptr;
	int x = *p;
```
until something kills the binary (this can be reproduced by using e.g. compact reporter, as it does not trigger the same error the console reporter does).
* The exception handling mode being set to asynchronous, i.e. using `/EHa` compiler flag. This causes a structured exception to be encountered twice, once in the vectored exception handler and once as a regular exception. The second time it breaks because it also forces a reporter to work after `testRunEnded` has been called because of the vectored exception handler.


## Takeaways
* "<binary> has stopped working" windows popping up is intended behaviour.
  * To avoid messing with debuggers and other programs that hook up to structured exception handlers, our handler does not swallow the exception after reporting, but passes it on. This usually means that it goes up to the system's handler, which kills the binary and reports a problem.
* Combination of C++/CLI and `CATCH_CONFIG_WINDOWS_SEH` will cause error overcounting and weird behaviour, but it should be fairly harmless.
  * There is no way to fix it, but it is possible to detect when code is compiled as C++/CLI and we could disable SEH instead. However, I think overcounting errors is better than possibly not reporting them.
* Combination of `/EHa` in general and `CATCH_CONFIG_WINDOWS_SEH` will cause error overcounting and weird behaviour, but it should be fairly harmless.
  * [As far as I can tell, MSVC does not provide macro to detect which version of exception handling is used.](https://msdn.microsoft.com/en-us/library/b0084kay.aspx) This means that even if we wanted to, Catch2 cannot autodetect this and disable SEH. Again, I think that overcounting is better than silently crashing + `/EHa` is relatively uncommon, so `CATCH_CONFIG_WINDOWS_SEH` will remain the default when compiled with MSVC, but I will add a note about this problem to the documentation.

**Comment by davidaue** [comment]
Thanks for looking at all of that. I can certainly live with things the way they are if there is no good solution.
