### ISSUE TITLE
StreamingReporterBase::assertionStarting should not be pure virtual

### ISSUE THREAD

**Issue by rcdailey** [catchorg/Catch2#1240]
I'm  using v2.1.2 of Catch and I noticed that a lot of methods are pure virtual when deriving from `StreamingReporterBase`. I am only interested in implementing these methods:

* `assertionEnded`
* `sectionEnded`
* `testCaseEnded`

I don't see the purpose of forcing subclasses to implement aspects of a reporter they do not want. Would it be reasonable to relax the interface requirements?

**Comment by JoeyGrajciar** [comment]
@rcdailey do you want to implement reporter or listener?

**Comment by rcdailey** [comment]
This is a really old issue. Users no longer have an option to implement multiple reporters, so this is probably a non-issue, assuming the listener interfaces do not do the same thing: force users to implement certain functions for no apparent reason.

**Comment by JoeyGrajciar** [comment]
Listeners are usually derived from `TestEventListenerBase` which overrides those virtual methods :) In case of reporters. Both listeners and reporters have the same interface as all are using `IStreamingReporter` interface class. Making it not pure virtual might not be a good idea but making an override inside the `StreamingReporterBase` could solve the issue as it can be overrided from other class too.

**Comment by rcdailey** [comment]
I'll go ahead and close this issue since architecture of this stuff has changed significantly since it was reported. Thanks for your feedback.

**Comment by philsquared** [comment]
@rcdailey The original issue was reported in April - unless I'm missing something. I don't think much, if anything, has changed with the reporter/ listener interfaces in that time.

I agree that it _sounds_ like you need a Listener rather than a Reporter - but it's not entirely clear.

Is your issue entirely resolved now - or do you still need some help? If so, perhaps you could give a bit more detail in what you are trying to do?

The difference between a reporter and a listener is that a reporter is intended to render events to some output stream (console, file, network etc) and should, by default, handle all events (ie: opt-out). A listener is just an in-code thing, that happens to map on to the same interface - but it's just for when you want to be notified of certain events - and therefore is opt-in - you only implement the handlers for the events you are interested in.
