### ISSUE TITLE
Add no-op test run mode for test discovery

### ISSUE THREAD

**Issue by vvuk** [catchorg/Catch2#1346]
Test discovery in a catch runner makes it difficult to integrate into external runner tools.  In particular, sections are not reported with any of the test case listing options, requiring an actual run to discover.

There are already multiple reporters available for test results that provide all of the info -- is it possible possible to add a no-op mode that would skip actually running the test code?  In other words, go through all the test cases and sections and report an "inconclusive/not run" overall result through the normal reporting path.

With this using the XML reporter would give detailed information on test cases and sections in a structured way, and additional reporters could be easily added if someone wants/needs test discovery done in a different way.

I realize that "just run the tests" would also work for discovery, though that's a challenge for long-running tests or ones that have external dependencies (attached hardware, running servers, etc).

**Comment by philsquared** [comment]
While such a reporter could be written (and this has been requested before - and it's not an unreasonable request in itself) - it wouldn't solve your problem.
The reason is that it would still actually run all the test code - even if it was only reporting the test case and section names. It has to, for the same reason you opened with, we have to run the code to discover the sections!

Perhaps you're suggesting that the "no-op" mode be exposed as a globally accessible flag that could be checked in the user test code to see if it needs to run the code or not? That could work, but would be hard to maintain, and I don't think would result in a very satisfactory experience.

If this is a problem for you I would recommend using fixture classes instead. It doesn't have the same nesting abilities as sections, but discovery is eager, at least.

Alternatively, I believe there are scripts that can parse the test cases and sections out of the source code! (although that breaks down if they are not sequential - e.g. if sections are dynamic and/ or in helper functions).

**Comment by vvuk** [comment]
Makes sense -- I wasn't sure what the structure of the generated code was like, if there was a way to essentially generate `if (!noOp) { ..; }`... but as I type that out I realize that won't work with how sections are implemented, with if checks to see if they've been already run.  Thanks for Catch2 by the way, it's been a pleasure to work with!
