### ISSUE TITLE
Need help with setup. Error LNK2019: unresolved external symbol.

### ISSUE THREAD

**Issue by janissimsons** [catchorg/Catch2#1366]
## Description
I added an empty project to an existing Visual Studio solution. There I added a .cpp file with:
`#define CATCH_CONFIG_RUNNER`
`#include "catch.h"`
`#include "../OtherProject/TestClass.h"`

`int main(int argc, char* argv[]) {
	int result = Catch::Session().run(argc, argv);
	return result;
}`

`TEST_CASE("Test Add")
{
	TestClass test1;
	auto result = test1.Add(4, 2);
	REQUIRE(result == 6);
}"`

After building the solution, I get unresolved symbol errors:
`0>TestsMain.obj(0,0): Error LNK2019: unresolved external symbol "public: __cdecl TestClass::TestClass(void)" (??TestClass@@QEAA@XZ) referenced in function "void __cdecl ____C_A_T_C_H____T_E_S_T____0(void)" (?____C_A_T_C_H____T_E_S_T____0@@YAXXZ)`

What am I doing wrong?

-------------------------------------
* Catch version: **v2.3.0**
* Operating System: **Win 10**
* Visual Studio 2017

**Comment by janissimsons** [comment]
I hadn't set the other project as a static library, it's working now. I didn't know exe projects can't be tested the same way.

**Comment by KubaO** [comment]
Uh, huh? Are you sure? Both ELF and PE formats make very minor distinctions between the "executable" and "dynamically linked library", and you can certainly export symbols from an executable EX and then dynamically link to them from another executable IM. On *both* Windows and Linux. And it works both via `dlopen`/`LoadLibrary` and by adding symbolic dependencies directly to IM (on Windows by using an import library for the other .EXE, on Unix by just linking to that other executable).

The problem here was lack of exported symbols, and the dimbulbness of MSVC's linker that IIRC still needs the stupid import libraries. Using mingw32 compiler and linker, you can link directly to other .EXE files on Windows :)

**Comment by plamensberberov** [comment]
@janissimsons Where did you read that .exe projects can't be tested that way and how are you supposed to test them?

**Comment by ClassyCircuit** [comment]
> @janissimsons Where did you read that .exe projects can't be tested that way and how are you supposed to test them?

I am sorry that was a long time ago and I am no longer working with C++, I really don't remember where I read it. 
But you should probably take into account what KubaO said about exporting symbols maybe then it will work.
