### ISSUE TITLE
Possible to capture an offending match in custom Matcher

### ISSUE THREAD

**Issue by mwpowellhtx** [catchorg/Catch2#1466]
Hello,

Using the most recent-ish v2 Catch. I might have asked a variation of this question before, but it's been a little while...

I am customizing my own [Matcher](/catchorg/Catch2/blob/master/docs/matchers.md) in order to verify a vector of supposedly capitalized terms. When one is discovered not to be capitalized, I want to capture that and report it meaningfully via the ``describe`` override.

So, the rub? You guessed it; the ``match`` method override prohibits changes to the ``Match`` class itself:

```C++
std::string offending_word;
// ...
virtual bool match(const std::vector<std::string>& words) const override {
    // ...
    offending_word = s; // this is a no-no!
    // ...
}
```

So... What is my recourse? I could throw a ``std::exception``?

**Comment by philsquared** [comment]
I think I do remember discussing this before (I think it must have been in [this](https://github.com/catchorg/Catch2/issues/1116) issue).

The problem is that `describe` is meant to be callable independently of a match - so it shouldn't rely on any state shared between the calls.
There are certainly cases, and this is one of them, where reporting detail from the match would be valuable. I think this has been discussed internally, too - but I'm not sure where we went with it.

You could work around it, for now, by making "offending_word` mutable, of course. That should work the way things are currently implemented (but make sure `describe` can handle the case that it is not set). It's possible it would be broken by future changes, though.

**Comment by mwpowellhtx** [comment]
Okay, so something like this, assuming the member:

```C++
int test;
```

Then in the ``match`` method, casting away the *constness*:

```C++
const_cast<int&>(test) = 1;
```

Duly noted, thank you...

**Comment by mwpowellhtx** [comment]
Output something like this:

```
  REQUIRE_THAT( capitalized_words, AllAreCapitalized<std::string>() ) with expansion:
  { "kLj1c", "y1DXSv", "wf7nnZf" } All words must have length and be capitalized.
  'kLj1c' was not capitalized

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed
```
