### ISSUE TITLE
unused variable warnings

### ISSUE THREAD

**Issue by rhd** [catchorg/Catch2#1552]
**Describe the bug**
Hi,

I have a testfile setup like this

```cpp
TEST_CASE("test case 1"){
  SECTION("section 1"){
  ..
  }
  SECTION('section 2"){
  ..
  }
}
```

I'm getting warnings from gcc4.8.1 about unused variables.

`error: unused variable 'catch_internal_Section2'` --> this points to "section 1"

`error: unused variable 'catch_internal_Section3'` --> this points to "section 2"

**Expected behavior**
No warnings

**Reproduction steps**
Steps to reproduce the bug.

**Platform information:**

 - OS: RHEL6
 - Compiler+version: **GCC v2.8.1**
 - Catch version: **v2.6.1**

**Additional context**
This didn't happen with catch 2.2.x

Thanks!

**Comment by horenmar** [comment]
Can you check which release actually introduced the warning for you?

I don't think it reproduces on more up-to-date versions of GCC, so I can't check on my own.

**Comment by rhd** [comment]
Hi,

It seems to happen between `2.2.1` and `2.2.2`: https://github.com/catchorg/Catch2/compare/v2.2.1...v2.2.2

And you're right, when I use gcc 4.8.5 on RHEL7, I do not get those internal catch section variable warnings. Unfortunately, for me, I'm stuck on RHEL6 with gcc 4.8.1.

Any ideas what would trigger the warnings?

**Comment by Chukak** [comment]
If you use cmake, you can try something like `incude_directories(SYSTEM "${CATCH_DIR}/single_include/catch2/")`

**Comment by rhd** [comment]
@Chukak great idea! Unfortunately, it doesn't help. I verified `-isystem <path to catch>` is on the command line but the internal unused variables still spill out.

**Comment by Chukak** [comment]
How about this:
```cpp
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"
#include "catch.hpp"
#pragma GCC diagnostic pop
```

**Comment by rhd** [comment]
To my surprise, the `#pragma` statements around the include _does not_ fix unused catch2 internal section variables from leaking out.

**Comment by horenmar** [comment]
Well yeah, because the pragma statements stop after the include, but they would need to apply to code generated in a `TEST_CASE` macro. 

Anyway, the commit that caused this change is 36417069232a62c7b774189cbb353844dd41f2db, which makes it so that Catch no longer leaks `#pragma GCC diagnostic ignored "-Wunused-variable"` into the whole file, and because the oldest GCC we test with is something like 4.8.3, it didn't cause any trouble.

Given just how old is your target compiler, I think I am going to go with "Won't Fix" on this one, because you can solve it locally by adding the pragma into the test TUs, and fixing it in master would worsen things for everyone else.


-------

As a side note, can you use dev-toolset? We are using it at my day job for our RHEL machines and it works pretty well.

**Comment by rhd** [comment]
@horenmar thanks. If it's not obvious why the unused variables leak out in gcc 4.8.1 - let's chalk this up to a crappy compiler. I'll see if we can use the dev-toolset compilers instead. I'll close this.

**Comment by gigglesun** [comment]
We used gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), it also have this issue. Our CI compiler have flags -Werror=unused-variable, it's sad that I broken our build.
