### ISSUE TITLE
Incorrect output to std::ostream with std::setw

### ISSUE THREAD

**Issue by 414d** [catchorg/Catch2#1623]
**The bug**
The std::setw incorrect works for user defined types.

**Expected behavior**
For instance for an empty struct the output to ostream or to ostringstream should be an empty string.

**Reproduction steps**
The following code prints 3 chars: ***
```
#include "catch.hpp"
#include <iostream>
#include <iomanip>

struct Test{};
std::ostream& operator<<(std::ostream& o, const Test&)
{
   return o;
}

TEST_CASE("Test1")
{
   std::cout <<std::setfill('*') << Test() << std::setw(4);
}
```
But the following code prints an empty string:

```
#include <iostream>
#include <iomanip>

struct Test{};
std::ostream& operator<<(std::ostream& o, const Test&)
{
   return o;
}

int main()
{
   std::cout <<std::setfill('*') << Test() << std::setw(4);
   return 0;
}
```

**Platform information:**

 - OS: **Arch Linux**
 - Compiler+version: **GCC v8.3.0**
 - Catch version: **v2.7.1**

**Additional context**
Usually I need to print to ostringstream in TEST_CASE. But I print to std::cout in these samples for simplicity.

**Comment by BillyDonahue** [comment]
The stars are being printed by the next thing streamed to `std::cout` AFTER "Test1".
Your repro is incomplete. You should say how you built and ran this little program to make the stars appear. I don't get any stars when I run it, because the next thing that hits std::cout is a huge row of equal signs.

I'd say it's incorrect to leave `std::cout` "armed" with a width of 4 like that. Leaving the `std::setfill` state like that is also sloppy. The next thing `std::cout` prints will be star-padded to 4 spaces, then the width reverts to 0, as width isn't sticky.

Any time a setting is made to `std::cout` flags, it's good manners to clear them out.

So if I add another `TEST_CASE`, then I see the padded stars from Test1's corruption of `std::cout`.


```
$ cat test.cpp

#include <iostream>
#include <iomanip>

#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>


struct Test{};
std::ostream& operator<<(std::ostream& o, const Test&)
{
    return o;
}

TEST_CASE("Test1")
{
    std::cout << std::setfill('*') << Test() << std::setw(4);
}

TEST_CASE("Test2")
{
    std::cout << "";
}

$ git -C $CATCH checkout master ; $CXX -o test -std=c++17 -I$CATCH/single_include test.cpp

$ ./test
****===============================================================================
test cases: 2 | 2 passed
assertions: - none -

```


It could be argued that the test framework should perhaps defensively try to clear any flags that were set on cout by an errant unit test I suppose. But that's not quite what this Issue is complaining about, I think.

**Comment by 414d** [comment]
You're right and I didn't understand enough the behavior of these functions (`std::setw `and `std::setfill`). Also I think the framework should not try to clear flags of STL.
