### ISSUE TITLE
Overloading operator ==

### ISSUE THREAD

**Issue by dolby360** [catchorg/Catch2#1653]
**Bug description**
No support for overloading operator ==

**Expected behavior**
Support for overloading operator ==

**Reproduction steps**
Attached below

**Platform information:**

 - OS: **Windows or Linux**
 - Compiler+version: **g++**
 - Catch version: **v2.8.0**

**Comment by dolby360** [comment]
code:
class add
{
public:
    add (int x) : _x( x ) { }
    operator int() { return _x; }
    add operator() (int y) { return add(_x + y); }
    friend bool operator == (const int& a, const add& b) { return a == b._x; }

private:
    int _x;
};


test:
TEST_CASE("A Chain adding function"){
    REQUIRE(add(1) == 1);
    REQUIRE(add(1)(2) == 3);
    REQUIRE(add(1)(2)(3) == 6);
}


exception:
error: invalid user-defined conversion from 'const add' to 'const int&' [-fpermissive]
     auto compareEqual( LhsT const& lhs, RhsT const& rhs ) -> bool { return static_cast<bool>(lhs == rhs); }

**Comment by horenmar** [comment]
Okay, where to start.

1) Your `operator==` takes lhs of `int`, rhs of `add`, while you are trying to compare lhs of `add` and rhs of `int` (and conceptually you probably want both sides to be `add`.
2) This means that when you want to do `add(1) == 1`, the lhs has to be converted to an `int` via `operator int()` and the rhs has to be converted to `add` via the implicit single parameter constructor.
3) This will then fail, because your `operator int()` is not const, but using it inside Catch requires it to be usable from a const context.
