### ISSUE TITLE
Custom precision in error reports not working for implicit conversions

### ISSUE THREAD

**Issue by kghose** [catchorg/Catch2#1828]
I find the [Custom precision](https://github.com/catchorg/Catch2/blob/master/docs/tostring.md#floating-point-precision) feature very useful. However it does not work with implicit conversions.

```
TEST_CASE("Precision bug")
{
    Catch::StringMaker<double>::precision = 20;

    struct Foo {
        double    val;
        operator double() const { return val; }
    };

    Foo    x = { 2600000. };
    double y = 2600000.0;

    REQUIRE(x == y);
    REQUIRE((double)x == y);
}
```

Output with `./tests -s`

```
/Users/kghose/Code/groho/tests/units_test.cpp:98: PASSED:
  REQUIRE( x == y )
with expansion:
  2.6e+06 == 2600000.0

/Users/kghose/Code/groho/tests/units_test.cpp:99: PASSED:
  REQUIRE( (double)x == y )
with expansion:
  2600000.0 == 2600000.0
```

The expected behavior is for these  implicit conversions to behave the same way as explicit casts. Note that this example behaves identically with or without the precision invocation.

Tested with Compiler: clang version 6.0.0

Thank you!

**Comment by horenmar** [comment]
Sorry, but the cost to support this is too high compared to the benefit.

The problem here is quite simple, the stringification effort goes through strictly defined steps

1) Look for a corresponding `StringMaker` specialization
2) Check if the type is streamable using `op<<`
3) Check if the type fulfills one of the conditions for special stringification, e.g. being range-like object
4) Give up and use "{?}" as a placeholder

If you use explicit cast, then the stringification sees a `double` and matches `StringMaker<double>` in the first step, which allows you to use explicit precision setting.

If you do not use explicit cast, then step 1) fails and Catch2 checks for `op<<`... and finds standard-provided `operator<<(std::ostream& lhs, double rhs)` and the compiler helpfully converts `Foo` to `double` to make it fit. However, at this point the conversion is out of Catch's hands and in the hands of stdlib.
