### ISSUE TITLE
v3: compilation fails on GCC 9.2

### ISSUE THREAD

**Issue by offa** [catchorg/Catch2#1856]
**Describe the bug**

The current *dev-v3* (1327946785cd33dcd0ed3142dcb6e8849ccbc893) fails to compile on GCC 9.2:

- `-Werror=unknown-pragmas` (PR submitted: #1855)
- `-Werror=parentheses` at [`__VA_ARGS__` expansion](https://github.com/catchorg/Catch2/blob/dev-v3/src/catch2/catch_capture.hpp#L48); wrapping the `__VA_ARGS__` into parentheses fixes the warning but causes a test failure
- `-Werror=address` and `-Werror=nonnull-compare` at [ostream << usage with](https://github.com/catchorg/Catch2/blob/dev-v3/src/catch2/catch_stream.h#L42)

**Expected behavior**

It should compile.

**Reproduction steps**

1. Use latest *dev-v3* (at 1327946785cd33dcd0ed3142dcb6e8849ccbc893) branch
1. Compile with CMake using GCC 9.2
1. First error (unknown pragma) ends the build

**Platform information:**

 - OS: **Linux**
 - Compiler+version: **GCC v9.2.0**
 - Catch version: **dev-v3**

**Additional context**

Also tested on Clang 9.0.1, no issues there.

**Comment by horenmar** [comment]
Yeah, the move to static library meant that `Werror` is temporarily disabled, and the warning suppression needs some changes, as we can no longer just say "this is a system header, do not propagate warnings that originate in here".

`-Wparentheses` will be especially painful, as it cannot be suppressed locally on older versions of GCC because of bugs in its handling of `_Pragma`.

**Comment by horenmar** [comment]
This should be fixed with current dev-v3 -- Werror is enabled again and CI passes.

@offa Can you confirm?

**Comment by offa** [comment]
Just tested with 75b711a3 and no errors. Thanks!
