### ISSUE TITLE
REQUIRE_THROWS does not suceed with method has throw() specifier

### ISSUE THREAD

**Issue by allanleal** [catchorg/Catch2#1914]
**Describe the bug**

Consider the following code (note the `throw()` specifier in method `Foo::execute`!):

~~~c++
class Foo
{
public:
    void execute(bool value) throw()  // this throw() specifier needs to be removed to get the test passing
    {
       throw std::runtime_error("error while calling Foo::execute()");
    }
};

Foo foo;

REQUIRE_THROWS( foo.execute(true) );
~~~

This test fails. It only succeeds if `throw()` is removed.

**Expected behavior**
The test should succeed with or without the `throw()` specifier in method `Foo::execute`.

**Reproduction steps**
See above.

**Platform information:**

 - OS: **Linux**
 - Compiler+version: **GCC v7.3.0**
 - Catch version: **v2.10.2**

**Additional context**
None.

**Comment by horenmar** [comment]
Do you know the semantics of `throw()` in function declaration? Or alternatively, can you explain why you think that it should succeed both with and without the specifier?

**Comment by allanleal** [comment]
>  why you think that it should succeed both with and without the specifier

The expression inside `REQUIRE_THROWS`, `foo.execute(true)`, always throw a runtime error. Thus, this test should always succeed. However, it fails with `execute` method is declared with `throw()`. This specifier is an explicit way of telling client code/users that this method may throw. One could even tell which exceptions may be raised using `throw(SomeException, AnotherException)`.

**Comment by horenmar** [comment]
Yeah, no.

The `throw` specifier has been deprecated in C++11 (and actually removed in C++17 if nonempty, C++20 if empty), but if it is empty, it means that the function _cannot_ throw, just like `noexcept` does. Just like `noexcept`, this contract is checked at runtime, and if it is violated, then, instead of propagating the exception outside of the function, a special handler is called. In case of `throw()` it is the unexpected handler, in case of `noexcept` it is the terminate handler.

**Comment by shishirlearnz** [comment]
As explained by @horenmar  , this isn't a bug. Request admin(s) to close this as Not a Bug.

**Comment by allanleal** [comment]
OK, all clear now. Thanks.
