### ISSUE TITLE
MSVC 19.25 build error

### ISSUE THREAD

**Issue by egorpugin** [catchorg/Catch2#1931]
`CHECK(R"xxx("\"")xxx");`
`error C2017: illegal escape sequence`
catch 2.12.1

**Comment by horenmar** [comment]
Seems like a [reoccurence of this MSVC preprocessor bug]( https://github.com/catchorg/Catch2/blob/master/docs/limitations.md#visual-studio-2017----raw-string-literal-in-assert-fails-to-compile).

**Comment by am11** [comment]
MS' CRT has a non-conformant preprocessor expansion behavior since the dawn of times. In VS 2017 15.8, [`/experimental:preprocessor`](https://docs.microsoft.com/en-us/cpp/build/reference/experimental-preprocessor) switch was added to support C99 conformant preprocessors, while keeping the defaults to classic (non-conformant) behavior. The experimantal trial ran its course in VS 2019 16.6, when `/experimental:preprocessor` was superseded by production-ready [`/Zc:preprocessor`](https://devblogs.microsoft.com/cppblog/announcing-full-support-for-a-c-c-conformant-preprocessor-in-msvc/) switch.


To wit:

```c++
// my-catches.cpp
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE("test") {
    CHECK(R"xxx("\"")xxx");
    CHECK(std::string(R"("\)") == "\"\\");
}
```
compile with:

```cmd
cl.exe my-catches.cpp /EHsc /Zc:preprocessor 
```

results in:

```cmd
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

my-catches.cpp
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winbase.h(9305): warning C5105: macro expansion producing 'defined' has undefined behavior
Microsoft (R) Incremental Linker Version 14.26.28806.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:my-catches.exe
my-catches.obj
```

running `my-catches.exe` produces:
```cmd
===============================================================================
All tests passed (2 assertions in 1 test case)
```
