### ISSUE TITLE
VCPKG for catch 3

### ISSUE THREAD

**Issue by davidhunter22** [catchorg/Catch2#1945]
I was wondering if there are any plans to make catch version 3 available though vcpkg?
Also if it will be will both be available for a while, maybe catch2 and catch3?

**Comment by horenmar** [comment]
Ask there. Around v2.5 I handed the updating over to the vcpkg maintainers.

However, I am not a fan of making them both be available next to each other, because of the way vcpkg works. There already is `catch`, `catch-classic`, and `catch2`, I don't think there should be even more packages with misleading names.
