### ISSUE TITLE
DeepCode found possible leaks

### ISSUE THREAD

**Issue by patlecat** [catchorg/Catch2#1951]
Running deepcode it found 7 possible leaks and 4 recommendations ([DeepCode](https://www.deepcode.ai/)):

Link to report: https://www.deepcode.ai/app/gh/catchorg/Catch2/0f12995501ee01d3d2bdd9f4978bb28b5f670bab/_/dashboard

**Comment by horenmar** [comment]
1) Why does the link need authorization?
2) Why does the authorization require so many rights?
3) Catch2 CI is already running with mem check.

All in all, nope.

**Comment by thebpc** [comment]
@horenmar the reason why DeepCode needs permissions are so the system can fetch the code on your behalf and analyze it. Otherwise, GH will throttle the DeepCode account. DeepCode also offers you continuous monitoring of your repos and alerts your (w/t comment) if a  PR introduces a new issue. All of this is fully customizable: which repos to monitor and when/if to comment on issues.

On your 1st  question, we will look into providing the results without the authorization required (i.e. without re-analyzing the code)
