### ISSUE TITLE
Performance hit for unreported successes in reporters derived from CumulativeReporterBase

### ISSUE THREAD

**Issue by Tridacnid** [catchorg/Catch2#1966]
**Describe the bug**
The following example test has a huge performance overhead when using a reporter derived from CumulativeReporterBase (junit, sonarqube), even when successful tests aren't being reported.

```
#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>

// other reporters
#include <catch2/catch_reporter_automake.hpp>
#include <catch2/catch_reporter_sonarqube.hpp>
#include <catch2/catch_reporter_tap.hpp>
#include <catch2/catch_reporter_teamcity.hpp>

#include <vector>

namespace
{
    constexpr const std::size_t LARGE_BUFFER_SIZE { 32 * 1024 * 1024 }; // 32MB
    using u_byte = unsigned char;
    std::vector<u_byte> generateLargeBuffer()
    {
        std::vector<u_byte> buffer( LARGE_BUFFER_SIZE );
        return buffer;
    }
}// namespace

TEST_CASE( "REQUIRE() 2 large vectors of bytes are equal" )
{
    auto buffer1 { generateLargeBuffer() };
    auto buffer2 { generateLargeBuffer() };

    // will take ~30s with junit/sonarqube reporter, but fractions of a second on other reporters
    REQUIRE( buffer1 == buffer2 );
}

```
I traced it down to the following call chain:
```
CumulativeReporterBase::assertionEnded()
  prepareExpandedExpression()
    AssertionResult::getExpandedExpression()
      AssertionResultData::reconstructExpression()
```

```
    std::string AssertionResultData::reconstructExpression() const {

        if( reconstructedExpression.empty() ) {
            if( lazyExpression ) {
                ReusableStringStream rss;
                rss << lazyExpression; // <- most of the time is spent in operator<<
                reconstructedExpression = rss.str();
            }
        }
        return reconstructedExpression;
    }
```

The xml reporter *does* take the performance hit if successful tests are reported (-s option), and that does show how silly the expansion of this expression is.

**Expected behavior**
Using the junit reporter should have similar performance as the xml reporter when successful results aren't being shown, especially when considering that `utest -r junit -s` doesn't display the expanded expression.

**Reproduction steps**
Steps to reproduce the bug.

Run the provided test with `-r junit` and `-r xml` and observe the difference.

**Platform information:**

 - OS: **Linux**
 - Compiler+version: **GCC v10.1**
 - Catch version: **v2.12.1**

**Addtional Note**
It seems incorrect to me that the junit reporter would include the reporter's processing time in the unit test time:
```
workspace/catch2junitslowdowntest/cmake-build-debug 
❯ time ./bin/utest -r junit
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="utest" errors="0" failures="0" tests="1" hostname="tbd" time="32.9809" timestamp="2020-06-21T04:46:41Z">
    <testcase classname="utest.global" name="REQUIRE() 2 large vectors of bytes are equal" time="32.980824"/>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>

real	0m33.012s
user	0m32.453s
sys	0m0.523s
```

Actually running the unit test's code is a small fraction of the time spent, comparing against the xml reporter's time:
```
workspace/catch2junitslowdowntest/cmake-build-debug 
❯ time ./bin/utest -r xml
<?xml version="1.0" encoding="UTF-8"?>
<Catch name="utest">
  <Group name="utest">
    <TestCase name="REQUIRE() 2 large vectors of bytes are equal" filename="/home/joe/workspace/catch2junitslowdowntest/main.cpp" line="23">
      <OverallResult success="true"/>
    </TestCase>
    <OverallResults successes="1" failures="0" expectedFailures="0"/>
  </Group>
  <OverallResults successes="1" failures="0" expectedFailures="0"/>
</Catch>

real	0m0.043s
user	0m0.018s
sys	0m0.025s
```

**Comment by Tridacnid** [comment]
I'm happy to take a stab at this one, but I need a bit of guidance on the best way to attack it. As far as I can see, `reconstructedExpression` is cached when `reconstructExpression()` is called. If we don't need the reconstructed expression at all in the junit reporter, I'd be inclined to write my own override for `assertionEnded()`. If that data is needed by the junit reporter but only with the `-s` option, it seems like the best attack vector would be to only evaluate and cache the expression if that option is enabled.

**Comment by horenmar** [comment]
Some quick notes first
* `CumulativeReporterBase` exists for reporters that can only write out their output retroactively, so it has to keep around the results, which means that the expansion must happen eagerly to avoid dangling ref issues.
* If the JUnit reporter does not need the decomposed expression, then the work is wasted.
* It is probably better to have a simple mechanism to signal up-the-stack whether the expansion is needed or not, rather than having the specific reporters override `assertionEnded`.
* From a quick look, `SonarQube` reporter only needs the expression for failed assertions.

All in all, I think the solution here is to extend `ReporterPreferences` with more members -- one for whether successful assertion's expansion will be used, and one for whether unsuccessful assertion's expansion will be used.

As for the duration reported, 🤷. I think there is an argument to be made for both behaviours, that is, reporting _total_ time used up by running that test, even though a lot of the time was taken up by "reporter's" overhead, or reporting time taken up only by code under test. I do not claim to understand JUnit format enough to know which one is preferred there.
