### ISSUE TITLE
Cannot convert 'Catch::SimplePcg32' to 'uint64_t' (aka 'unsigned long long') without a conversion operator

### ISSUE THREAD

**Issue by TERMIK** [catchorg/Catch2#2030]
Hello.
I've included the header file "catch.hpp" in my iOS application where I have a C++ part and defined #define CATCH_CONFIG_MAIN in a cpp file that I want to be tested. 

I've also written a simple test:

int return_int(int arg){
    return 1;
}

TEST_CASE( "Test", "[int]" ) {
    REQUIRE(return_int(1) == 1);
    REQUIRE(return_int(2) == 1);
}

But all I have are these two errors in the catch.hpp file:
Assigning to 'uint64_t' (aka 'unsigned long long') from incompatible type 'Catch::SimplePcg32'
Invalid operands to binary expression ('uint64_t' (aka 'unsigned long long') and 'Catch::SimplePcg32')

<img width="985" alt="Screenshot 2020-09-21 at 16 10 44" src="https://user-images.githubusercontent.com/5457854/93770694-31efa580-fc25-11ea-9889-53d4674fdb9b.png">

Compiler: Apple clang version 12.0.0 (clang-1200.0.32.2)

**Comment by horenmar** [comment]
Okay, I see what's happening. In the `TestHasher` function, there are two symbols with the name `rng`:

* a `Catch::SimplePcg32& rng()` free function, and
* a `Catch::SimplePcg32& rng` reference.

For some reason, AppleClang (and only AppleClang) decides that the free function is the one being referred to, rather than the reference.

Not sure if this is an AppleClang bug, bug in other compilers, or ambiguity in the standard, but it should be easy enough to work around this.
