### ISSUE TITLE
Test type and value at once

### ISSUE THREAD

**Issue by johnmcfarlane** [catchorg/Catch2#2201]
**Description**

2-in-1 type and value comparison:

```c++
auto expected{4};
auto actual{2+2U};
REQUIRES(expected == actual); // passes: the value is correct
STRICTLY_REQUIRES(expected == actual); // fails: the type is incorrect
```

**Additional context**

For certain libraries, it's important when testing the output of APIs that the type is correct. [Here](https://github.com/johnmcfarlane/cnl/blob/main/test/unit/scaled_integer/scaled_integer_common.h#L1154) is a rather convoluted example of my [`identical`](https://github.com/johnmcfarlane/cnl/blob/46d14197d48e9afb7661ca9286c7492001def351/include/cnl/_impl/type_traits/identical.h#L20) predicate in use. It tests for equality -- just like a common-or-garden unit testing macro -- but it also emits a compiler error if the types don't match.

For most cases, you don't want this because it'll make tests brittle and discourage use of `explicit`. But you sometimes do want to test the type -- especially in a library like CNL where so much of the computation is performed at compile time and encoded in return types. `identical` is great, but it doesn't print out the unequal values when used at run-time. A macro like this would be invaluable.

**Comment by horenmar** [comment]
I do not intend to add a special macro for this. I think the use of such macro would be very niche, and different users would have different requirements on the actual type-equivalence, e.g. should the equivalence be exact, including cv qualification? Should the equivalence be done after stripping cv qualification? Should the types be compared after decaying them? Should same base classes be accepted? etc

The good news is that you can write something relatively similar yourself, using the new Matchers interface. It would end up looking something like `REQUIRE_THAT(actual, Equals(expected) && HasType<SomeType>())`.

**Comment by johnmcfarlane** [comment]
> should the equivalence be exact, including cv qualification? Should the equivalence be done after stripping cv qualification? Should the types be compared after decaying them?

Those are really interesting questions. While that might be useful, I'm not even sure how I'd test for most of that. As this facility is mostly testing the return value of an API, such qualification isn't really a focus. Whenever I've used `is_same_v` instead, and had to wrestle with the correct constness of the expected type, I've only found it to be unwelcome noise.

> It would end up looking something like REQUIRE_THAT(actual, Equals(expected) && HasType<SomeType>()).

That's very expressive. Presumably `SomeType` would be `decltype(expected)`. Hopefully there is a way that the type can be tested statically. Also, I guess I'd have to add this definition to a header which includes `<catch2/catch.hpp>` and include that instead in all my tests. I'll try to figure something out next time I try out Catch2. 

Thanks

**Comment by horenmar** [comment]
> Presumably SomeType would be decltype(expected).

Maybe. Maybe not. Depends on how you came up with expected, and since `Equals` already exists and supports cross-type comparison (its argument and what it receives can be different type, as long as there is `==` that accepts them), `expected` might be different type than the one you want to get. Also see the problems with whether you want cv-qualified type comparison or not, and so on...

If someone shows me good arguments for what the implementation of `HasType` should do to make it both expert friendly and common-user-non-surprising, I would add it to first party provided matchers. However, I currently do not know of such arguments, so I want to avoid implementing it and potentially having to keep around bad implementation for legacy reasons.



> Hopefully there is a way that the type can be tested statically.

You can `static_assert` inside `HasType::match`, but my experience is that I might not always want my type tests compilation failures, which is why `STATIC_REQUIRE` can be switched between checking at runtime and checking during compilation.
