### ISSUE TITLE
there is no way how to enable C++17 features in the static build (3.0 preview 3 and devel too)

### ISSUE THREAD

**Issue by hanickadot** [catchorg/Catch2#2210]
**Describe the bug**
If I'm using static build and can't touch catch2 source code / directory, I'm unable to enable c++17 mode. And when I'm using the static build I'm getting link errors like:

```
Undefined symbols for architecture x86_64:
  "Catch::StringMaker<std::byte, void>::convert(std::byte)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > Catch::Detail::stringify<std::byte>(std::byte const&) in hash.cpp.o
```

**Expected behavior**
There should be a way how to ask the static build to be build in 17 mode or even better, the static build should be build in 17 mode, and only headers should enable/disable features..

**Reproduction steps**
Steps to reproduce the bug.

```c++
#include <catch2/catch_test_macros.hpp>
#include <cstddef>
#include <array>

TEST_CASE("problem") {
	std::array<std::byte, 4> arr{};
	REQUIRE(arr[0] == std::byte{0});
}
```

and link it against `Catch2::Catch2WithMain` without setting `-DCMAKE_CXX_STANDARD=17` globally and mark your target as `target_compile_features(target_name INTERFACE cxx_std_17)` then you will get a link error complaining about missing `std::string StringMaker<std::byte>::convert(std::byte value)`

**Platform information:**

 - OS: macOS 11.3
 - Compiler+version: cmake 3.19.3
 - Catch version: 3.0 preview 3 and devel commit `e8cdfdca87ebacd993befdd08ea6aa7e8068ef3d`

**Additional context**
Personally think that the static library should be build without highest possible standard switch available.

**Comment by horenmar** [comment]
So, the problem here is two-fold.

1) Fundamentally, C++ does not support mixing libraries/objects that were compiled using different settings, or with different compilers, or against different version of libraries. Doing so is a quick way to get into the IF;NDR territory, e.g. via odr violation.
2) CMake only propagates use requirements (e.g. standard library) in one direction, from depencies to their dependees. This is sufficient for things like library's include directories and link dependencies, but wholly insufficient for handling things like target C++ standard, which needs to be the same across all parts of a binary artifact. 

What Catch2 currently does is to declare usage of C++14, so that if a project depends on it, it will be compiled with at least C++14. I think this is wrong for long term usage, but it is convenient to get quickly started. However, if you target a newer standard than C++14, you need to ensure that Catch2 also compiles against that standard, either by manually adding the C++17 feature to the Catch2 target, or by telling CMake to use the newer standard globally (`DCMAKE_CXX_STANDARD=17 from command line, or `set(CMAKE_CXX_STANDARD 17)` from the CMakeLists.txt).

The reason to prefer the latter approach is that if you have multiple dependencies, say you also want to use the excellent `fmtlib`, you will not have to change them separately, which you would have to do with the former approach.

**Comment by dimztimz** [comment]
>  2. CMake only propagates use requirements (e.g. standard library) in one direction, from depencies to their dependees. This is sufficient for things like library's include directories and link dependencies, but wholly insufficient for handling things like target C++ standard, which needs to be the same across all parts of a binary artifact.

There are no problems to link together two object files that were compiled with different standard version into a single program. All major compilers promise this.

> However, if you target a newer standard than C++14, you need to ensure that Catch2 also compiles against that standard, either by manually adding the C++17 feature to the Catch2 target, or by telling CMake to use the newer standard globally (`DCMAKE_CXX_STANDARD=17 from command line, or `set(CMAKE_CXX_STANDARD 17)` from the CMakeLists.txt).

This works only if you compile Catch2 from source. You miss the case where Catch2 is consumed via package manager. In that case this is a bug and there is no workaround that the consumer can do. I already sent two PRs that fix this issue #2193 and #2196 (one for v3 and one for v2).

If you do not like that approach because the standard there can vary between platforms/compilers, please consider the following two approaches:

1. Compile the .cpp files always in C++17 mode, but make the headers consumable from both C++14 and C++17. This reduces the possibilities for ODR violations in the future. GCC 5 will still be supported this way because your code already uses feature test macros to detect C++17 features. With this we remove the variability of the version of the standard that I have in my PRs.
2. Move all C++17 features into headers.

**Comment by jayeshbadwaik** [comment]
> There are no problems to link together two object files that were compiled with different standard version into a single program. All major compilers promise this.

This is a chicken-egg scenario. The compiler promise ABI stability because people use/write libraries in the manner that is being suggested here. In future, there's a possibility of ABI breaking. In that situation, these measures will just cause more pain. 

> This works only if you compile Catch2 from source. You miss the case where Catch2 is consumed via package manager. 
 
 A good development package manager will allow you to select a C++17 version of Catch2.  The correct way to selecting a C++ standard for any library you want to build is to pass it as a command line parameter in the build step: `-DCMAKE_CXX_STANDARD=20`.  
 
 Anything else is a needless complication of the build script and will come to bite you back later. For example, in one of your commits what is basically happening is that if `CMAKE_CXX_STANDARD` is not set and compiler supports c++17, then C++ 17 is enabled. This causes silent errors for someone who is compiling with C++14. Or will cause errors in future with C++20. Fixing a build script then would be a breaking change to the build.

All the other approaches you suggested are significant work on the maintainer of the project. And much more unbounded work in future. The same situation is going to happen with C++20, and then with C++23. The alternative of compiling Catch2 with `-DCMAKE_CXX_STANDARD=17` is much lower and should be preferred.

**Comment by horenmar** [comment]
> There are no problems to link together two object files that were compiled with different standard version into a single program. All major compilers promise this.

So, this is only true under a significant caveat, which is that all symbols common to both of the object files must have the same definition. If this is not true, IF;NDR due to the ODR violation. This is the reason why so much time is spent on discussions around ABI stability, conditional compilation and polyfilling types.

Now, for Catch2 _at this moment_, I am unaware of functions/types whose definition changes based on the C++ standard used during compilation (as opposed to an overload/specialization being present or not). However, this has not always been the case (IIRC there used to be polyfilled smart pointer type), and I do not intend to keep it that way if I think having different definitions across different standard versions provides an improvement (e.g. using `std::format` for faster stringification when possible).


As to dependency managers, any dependency manager worth its name should let you specify flags with which the dependencies should be built, and also should check that your current build flags are equal with the build flags of the dependency you use. If you are using the system package manager, then this doesn't apply, but you generally shouldn't rely on the system package manager for your C++ dependencies, because its goals are different from yours.

The goal of the system package manager is to provide _your system_ with a set of libraries and binaries that play well together, compiled with consistent c++ standard and targetting a consistent c++ stdlib, compiler version, etc, not to let you build different packages in different versions for specific projects.

**Comment by bernhardmgruber** [comment]
I hit exactly this problem now, since vcpkg switched to install Catch2 v3 now on some GitHub CI runners where the compiler defaults to C++14 but my project uses C++17.

Although I might be able to solve this by making vcpkg compile Catch2 v3 with C++17 enabled, I keep wondering how I should use Catch2 v3 locally with vcpkg, where I also want to use it with various projects using different C++ standards. Please give this another thought!

**Comment by czrocklee** [comment]
Just FYI. I'm consuming the 3.0.1 version from Conan @toge added recently. I've found the same linking error but could be resolved by supplying `compiler.cppstd=20` to the profile. Exactly as @jayeshbadwaik suggested I suppose.
