### ISSUE TITLE
Build a static (or shared) library with test cases, and then link it with the main test file

### ISSUE THREAD

**Issue by weslleyspereira** [catchorg/Catch2#2234]
**Description**
Is it possible to build a static (or shared) library with test cases, and then link it with the main test file?
I tried and couldn't find any way of doing that.

**Additional context**
I would like to generate a test library that could test different implementations of my functions.

**In more details**
I am using a simple `tests_main.cpp`:
```c++
#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>
```
and test files with
```c++
#include <catch2/catch.hpp>
TEMPLATE_TEST_CASE( ... ) {
...
}
...
```

This build works:
```sh
/usr/bin/g++-7 -g -rdynamic test/blas/CMakeFiles/tester.dir/tests_main.cpp.o test/blas/CMakeFiles/testBLAS.dir/src/test_corner_cases.cpp.o test/blas/CMakeFiles/testBLAS.dir/src/test_inf.cpp.o test/blas/CMakeFiles/testBLAS.dir/src/test_nan.cpp.o -o test/blas/tester
```
but the following one doesn't have any of my test cases
```sh
/usr/bin/ar qc lib/libtestBLAS.a  test/blas/CMakeFiles/testBLAS.dir/src/test_corner_cases.cpp.o test/blas/CMakeFiles/testBLAS.dir/src/test_inf.cpp.o test/blas/CMakeFiles/testBLAS.dir/src/test_nan.cpp.o && /usr/bin/ranlib lib/libtestBLAS.a
/usr/bin/g++-7 -g -rdynamic test/blas/CMakeFiles/tester.dir/tests_main.cpp.o -o test/blas/tester  lib/libtestBLAS.a
```

Does anyone have a clue? Thanks.

**Comment by orlandini** [comment]
Hello there,

we do something similar in our library, perhaps it could be useful for you:

https://github.com/labmec/neopz/blob/76035e53944c6134a902129668b97caac5c698c5/UnitTest_PZ/CMakeLists.txt

**Comment by weslleyspereira** [comment]
> Hello there,
> 
> we do something similar in our library, perhaps it could be useful for you:
> 
> https://github.com/labmec/neopz/blob/76035e53944c6134a902129668b97caac5c698c5/UnitTest_PZ/CMakeLists.txt

If I understood it correctly, NeoPZ has a target `test_library` with the only source being `test_main.cpp`. Then all the tests depend on this library, right? I was trying to do the inverse, i.e., I would like to have a target `test_library` containing all my tests. In any case, I am looking at your example to see if I can use it. Thanks!

**Comment by ferdnyc** [comment]
@weslleyspereira Did you ever get it working?

I'm not sure it _could_ work, TBH, because of the way the Catch macros are set up, and because of this point in the documentation (The intro to "Supplying main() yourself"):
> The easiest way to use Catch is to let it supply `main()` for you and handle configuring itself from the command line.
> 
> This is achieved by writing `#define CATCH_CONFIG_MAIN` before the `#include "catch.hpp"` in exactly one source file.

Problem is, when the shared library is built, there won't be **any** file with `main()` in it, so none of the Catch2 setup "stuff" will get done. I think that's why there are no tests in your library after building. 

Catch2's macros mangle the names of the test cases and keep track of which were defined when the executable is built (so that things like `--list-test-names-only`, and therefore CMake automated test discovery, can work), creating a library would mean (even if you succeeded) you'd end up with multiple sets of test cases all glommed together and nothing keeping track of what's in there.

The macro-based nature of Catch seems to preclude writing the test cases _themselves_ as library functions. I can't think of a way around that, in a way that would still let you use things like the `CHECK()` macro in your library code. But, maybe someone else will have a more clever suggestion.

We do something like what @orlandini does, and have our `catch_main.cpp` defined as the source for a CMake `OBJECT` library that gets used as one of the `target_link_libraries()` for each of our test executables. That was done mostly to speed up compilation, especially building under MinGW. But our library tests are still built as separate executables, one executable per test file (which means one per class tested, in our current arrangement), each linked with the library itself and the `catch_main.cpp.o` that our `OBJECT` library outputs.

(To be honest, I have to say that I've come around to the idea of many individual test executables, and wouldn't want to go back to a monolithic test runner even if I could. We previously had a lot of problems testing parts of our library, stemming from side effects of certain classes, (Frickin' singletons.) Running in the same process, tests that either altered the state of the singletons or depended on a particular state would foul each other up. Now that each test runner is a separate process, it helps keep them isolated from each other.)

**Comment by weslleyspereira** [comment]
Sorry for the long time to comment on that one. I was working on other stuff and never had time to come back to the tests' design.

Thanks for the detailed explanation, @ferdnyc!

> (To be honest, I have to say that I've come around to the idea of many individual test executables, and wouldn't want to go back to a monolithic test runner even if I could. We previously had a lot of problems testing parts of our library, stemming from side effects of certain classes, (Frickin' singletons.) Running in the same process, tests that either altered the state of the singletons or depended on a particular state would foul each other up. Now that each test runner is a separate process, it helps keep them isolated from each other.)

I end up taking the same path, i.e., using one executable for each tester. This is better for unit testing I think.

I am closing this issue.

**Comment by ferdnyc** [comment]
@weslleyspereira Yeah, [as I recently noted](https://discourse.cmake.org/t/highly-duplicate-data-in-cmake-install-cmake-files/5816/2?u=ferdnyc) over @ the CMake Discourse, there are actually **two** big benefits to separate test executables:
1. The isolation from side effects, which in a monolithic test system can cause tests to interfere with each other.
2. Your tests are inherently parallelizable, even if the code you're testing isn't thread-safe and has no real intrinsic support for parallelism. (As I qualified, that's true **unless** your tests do anything really stupid, like depend on each others' data files. But as long as you grasp the basic concept of "unit" tests and don't actively make an _effort_ to sabotage yourself, tests built as separate executables can be executed in parallel by systems like CTest.)

     (**Edit:** We actually ended up disabling parallel test execution on Windows (MinGW), because it was causing strange test failures for reasons that weren't immediately obvious, and I ended up just deciding I didn't care enough to track down. But on Linux and MacOS, our test configuration automatically runs as many simultaneous tests as the system has CPU cores.)

**Comment by weslleyspereira** [comment]
> @weslleyspereira Yeah, [as I recently noted](https://discourse.cmake.org/t/highly-duplicate-data-in-cmake-install-cmake-files/5816/2?u=ferdnyc) over @ the CMake Discourse, there are actually **two** big benefits to separate test executables:
> 
> 1. The isolation from side effects, which in a monolithic test system can cause tests to interfere with each other.
> 2. Your tests are inherently parallelizable, even if the code you're testing isn't thread-safe and has no real intrinsic support for parallelism. (As I qualified, that's true **unless** your tests do anything really stupid, like depend on each others' data files. But as long as you grasp the basic concept of "unit" tests and don't actively make an _effort_ to sabotage yourself, tests built as separate executables can be executed in parallel by systems like CTest.)
>    (**Edit:** We actually ended up disabling parallel test execution on Windows (MinGW), because it was causing strange test failures for reasons that weren't immediately obvious, and I ended up just deciding I didn't care enough to track down. But on Linux and MacOS, our test configuration automatically runs as many simultaneous tests as the system has CPU cores.)

I agree. Thanks again!

About your first bullet: the developers of a software project I collaborate were spending lots of time to validate new testers and new functionalities in the code. This was because it took them too much time to compile the tester. Also, some of the developers lack knowledge of git. It happened a couple of times that some branch conflicts would make a test file not to compile, and the not experienced developer would spend time solving the issue instead of working on their project. Those two issues were solved by breaking the monolithic tester.
