### ISSUE TITLE
Easier reporter customization

### ISSUE THREAD

**Issue by loximann** [catchorg/Catch2#2259]
**Description**
The documentation and the API could be improved to make it easier to use custom reporters.

**Additional context**
I needed a slightly tweaked version of the JUnit reporter (the result can be seen [here](https://gitlab.com/loximann/custom-junit-reporter-demo)), and I noticed a two things:
1. The documentation on [Writing your own reporter](https://github.com/catchorg/Catch2/blob/devel/docs/reporters.md#writing-your-own-reporter) pretty much only says that "At time of writing the interface is subject to some changes so is not, yet, documented here.". I see some changes in version 3, but not huge. What are the plans? Should this be now documented?
2. The JunitReporter class is not extensible: the only way I figured out how to fix it was to duplicate the class and add the functionality I needed. Although the class architecture does not make it very easy to extend, modifying the class API a bit made it possible for me to do what I needed (see [here](https://github.com/catchorg/Catch2/compare/v2.x...loximann:junit_custom_section)). I wonder if there is wider need to support writing custom properties for each test case.
3. Certain components can be only reused in a hacky manner. The only easy way was writing all the code in the same file as main.cpp, where CATCH_CONFIG_RUNNER had been defined. Defining my class inheriting from CumulativeReporterBase was only possible by defining CATCH_CONFIG_EXTERNAL_INTERFACES. There were a few additional components I wanted to reuse (isWhiteSpace, isBreakable, isBreakableAfter, Column) which I did not figure out how to reuse in external code.

Let me know what you think. I can prepare pull requests for the first two points. but I am not sure how to address the third one.

**Comment by horenmar** [comment]
I am going to take it from the back.

ad 3: Yeah, v2 added things into "external interfaces" in a very ad hoc manner. Originally it didn't exist, and it was created for reporters, and some functionality that used to be defined in the "test file configuration" of `catch.hpp`, stopped being so, and somebody complained. For v3 the different model means that you can just include whichever header you want. 

Obviously, reaching too far into the internals might mean that they reach back and things break later -- this is also something I haven't quite figured out yet, which parts should definitely be internals, which parts should not, and how to best signal the differences... Especially once we start talking about e.g. `StringRef`, which is definitely an internal type, but also can be used by the user, e.g. when writing custom reporter.


ad 2: I am leaning towards recommending that customization of built-in reporters is done by copying them out, and changing them as needed. IIRC they are currently `final` in v3, because I want freedom to change them as long as the output is roughly the same.


ad 1: More changes are planned, namely significant changes to the events that are being reported.
  * I intend to remove the `testGroup*` events. They currently fully overlap with the `testRun*` events, and I do not see a way to make them distinct and useful (in theory, `testGroup` events should distinguish between different filters, but they do not nor could I find a time when they did).
  * I want to introduce new events for individual test case runs. The current `testCase*` events fire only once per `TEST_CASE`, while these would fire once for each path through `TEST_CASE`.
  * I want to remove the implicit sections in `TEST_CASE`.
  * After these are done, I also want to quickly go through the data types involved in the above, and see if some of them could be made more efficient through e.g. `StringRef`, or better ownership.

The last is the lowest priority of them, and if I don't have the energy to do it, then 🤷  But the others need to be done, and will change the resulting documentation.

There is also some work done on supporting multiple parallel reporters, but I don't remember if that requires changes to the reporter interfaces or not.


-----------------

I actually poked at the event rework during this week, but it turns out that the built-in reporters are, uh, adapted, towards the current non-sensical state, and unraveling the assumptions and dependencies will take a while.

**Comment by horenmar** [comment]
@loximann If you are still interested, the changes to reporters are mostly[^section-event-changes] done, so the documentation can be written without being immediately outdated. I can provide you some notes on what should be mentioned in the docs.


[^section-event-changes]: The last missing change is to make it so that a test starting does not also send a section starting event, but the more I think about it the less I think it is a good change.

**Comment by loximann** [comment]
Yes! Sorry I forgot to reply. I remember seeing the notification, but these two weeks have been mental. I don't know how I miraculously thought of this now...

But yes please, tell me how we proceed!

**Comment by horenmar** [comment]
I left the more detailed notes in a different country, but the gist is that the docs should provide

* List of customizable events
  * Their meaning
  * When are they sent and how they nest (e.g. that test run starting will always be sent before test case starting, which will be sent before partial test case start, etc)
* Mention the *reporter base helpers for writing custom reporters
* How to be a good citizen in the ecosystem
  * Verbosity settings if meaningful
  * Customizing `ReporterPreferences`
* Registering reporter factory


Given that the event list is shared with listeners, listeners should either link to it, or maybe it should be in its own documentation page and both reporters and listeners should link there :shrug: (I think that having both reporters and listeners in single doc page would make the resulting page too large)

**Comment by loximann** [comment]
Agh, sorry I wasted your time with this. Other things got my attention, yadda yadda :-/

**Comment by horenmar** [comment]
's okay
