### ISSUE TITLE
Handled SEH exceptions cause test failures

### ISSUE THREAD

**Issue by devin122** [catchorg/Catch2#2286]
**Describe the bug**
Throwing an SEH exception causes the current test to fail, even if the exception is caught within the body of the current test

**Expected behavior**
Tests should not fail for SEH exceptions which don't escape the body of the function.

**Reproduction steps**
```
#include <catch2/catch.hpp>
#include <Windows.h>

void func() {
  __try {
    *((volatile int*)0) = 0;
  } __except (EXCEPTION_EXECUTE_HANDLER) {
    puts("Exception handled");
  }
}
TEST_CASE("SEH_TEST", "[demo]") {
  func();
  puts("Everything is ok!");
  CHECK(true);
}
```

**Platform information:**

 - OS: **Windows 10**
 - Compiler+version: **MSVC 2017**
 - Catch version: **v2.13.7**

**Additional context**
Problem occurs because Catch2 registers an exception handler via `AddVectoredExceptionHandler()`, however vectored exception handlers are executed before walking the frame based exception handlers. I would think that Catch2 should be using frame based handlers to ensure that any tested code has a chance to handle the exception itself first (although I don't know how practical that is with the existing code)

**Comment by alabuzhev** [comment]
+1. `AddVectoredExceptionHandler`, despite the name, is not a proper way to handle SEH.
It is a first-chance mechanism, designed mostly for [debuggers](https://docs.microsoft.com/en-us/archive/msdn-magazine/2001/september/under-the-hood-new-vectored-exception-handling-in-windows-xp).

In particular, this breaks MSVC AddressSanitizer-enabled builds, because, apparently, ASAN uses SEH for its internal shenanigans:
```
`anonymous namespace'::reportFatal
Catch::handleVectoredException
ntdll.dll!RtlpCallVectoredHandlers
ntdll.dll!RtlDispatchException
ntdll.dll!KiUserExceptionDispatch
__asan::AddressIsPoisoned
__asan::QuickCheckForUnpoisonedRegion
__asan_wrap_memmove
std::_Copy_memmove
std::_Copy_unchecked
std::copy
____C_A_T_C_H____T_E_S_T____0
```

If Catch needs to handle SEH, it should wrap its `Session::run()` into `__try` / `__except` or, alternatively, [install](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-setunhandledexceptionfilter) a top-level filter for *unhandled* exceptions, not intercept every single exception in the process and panic.

**Comment by jiridanek** [comment]
Thankfully, the workaround of disabling SEH in Catch2, as suggested on #898, saves the situation here.

    #define CATCH_CONFIG_NO_WINDOWS_SEH
