### ISSUE TITLE
Ability to list benchmarks missing

### ISSUE THREAD

**Issue by mika-fischer** [catchorg/Catch2#2290]
**Describe the bug**
There seems to be no way to list all benchmarks analogous to `--list-test-names-only` or `--list-tests`

**Expected behavior**
There should be a way to list the names of the benchmarks programatically

**Additional context**
I want to integrate our C++ benchmarks with asv using [the recommended approach](https://github.com/airspeed-velocity/asv/issues/649#issuecomment-493740171). For this it would be very useful to get a list of all benchmarks without having to actually run them.

**Comment by horenmar** [comment]
Retrieving all benchmarks statically is impossible. 

It might be possible to have some sort of "skip benchmarks" mode, to speed up dynamic benchmark retrieval (tests would be normally run, but the internals of a benchmark would be skipped), but benchmarks are discovered dynamically so their containing test case has to be run.

**Comment by dadair-aptiv** [comment]
So thoughts on this since I was thinking about the same thing. You could do tags such as `[benchmark]` and skip during executable run (I haven't tested this so not sure if this works with benchmarking within Catch2). Another thought I had was in the build process have a separate rule to include benchmark files that contain only benchmark tests. 

The second solution I feel is less elegant but maybe not.

**Comment by horenmar** [comment]
There is now in fact a [`--skip-benchmarks`](https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md#skip-benchmarks) flag. It is still not possible to enable static listing of benchmarks, but in theory you can run the binary twice, once to list them and the second time to run them, without spending time to run them the first time.
