### ISSUE TITLE
CHECK_THROWS test passes with incorrect exceptions

### ISSUE THREAD

**Issue by nandanvasudevan** [catchorg/Catch2#2371]
**Describe the bug**
I was trying out https://github.com/nlohmann/json and wanted to test the exception mechanism it had.
My initial attempt was to use `CHECK_THROWS` but that was really difficult since [`nlohmann::json::out_of_range`](https://github.com/nlohmann/json/blob/e4643d1f1b03fc7a1d7b65f17e012ca93680cad8/include/nlohmann/detail/exceptions.hpp#L203-L216) is not easy to construct.
[`CHECK_THROWS_AS`](https://github.com/nandanvasudevan/cpp_scratch_pad/blob/3d274f7f62cf307a6be4414b8fb1f647f7a3ca94/src/main.cpp#L37-L38) was what I was supposed to use and that worked fine.
https://github.com/nlohmann/json/issues/3352

Before figure that out I tried `CHECK_THROWS` with `std::out_of_range` and to my surprise that worked! The test also passed with `std::bad_alloc`.

I am not sure if this is to be expected since `nlohmann::json::out_of_range` is derived from std::exception.

**Expected behavior**
I would expect `CHECK_THROWS` with `std::out_of_range` and `std::bad_alloc` to fail.

**Reproduction steps**
Steps to reproduce the bug.

Minimal example here: https://github.com/nandanvasudevan/cpp_scratch_pad/tree/json_parsing

**Platform information:**

 - OS: **Ubuntu Jammy Jellyfish (development branch)**
 - Compiler+version: **GCC v11**
 - Catch version: **v3 Preview 4**

**Additional context**

**Comment by nandanvasudevan** [comment]
If `CHECK_THROWS` does not verify with the second parameter, the actual type of the exception, why would it be required?

**Comment by horenmar** [comment]
`CHECK_THROWS` only requires single argument, the expression. It _allows_ multiple "arguments", because it is a variadic macro to support expressions like this `std::pair<T1, T2>(a, b)`, but whatever you pass in is still treated as a single expression.

This means that `CHECK_THROWS(foo(), std::exception())` checks that the expression `(foo(), std::exception())` throws, which it does if `foo()` throws. What should tip you off that you are doing something wrong is that `std::exception()` constructs an instance of `std::exception`, and does not provide type to catch.

**Comment by nandanvasudevan** [comment]
> checks that the expression `(foo(), std::exception())` throws, which it does if foo() throws.

If it doesn't really use the exception parameter, why should it be passed in? I fail to understand how an instance of **any exception** aids it's functionality.
