### ISSUE TITLE
Catch2 release schedule

### ISSUE THREAD

**Issue by rabauke** [catchorg/Catch2#2402]
**Description**
Not really a feature request, more a question. 

- When can we expect the release of version 3.0.0?
- How save is to use version 3.0.0-preview4? 
- Do I have to expect breaking changes for release version 3.0.0?

**Additional context**
I would like to employ Catch2 as our main test framework in a larger new project. Version 3.0.0 will offer some features that will be very useful for us (test reports in several output formats, faster builds, etc.) I need more information about the release plans for Catch2 in order to estimate the risks (and potential benefits) of using a pre-release version of Catch2 version 3.x.

**Comment by horenmar** [comment]
> When can we expect the release of version 3.0.0?

Hard to say. I am down to one large issue that needs to be done before v3 is ready (due to the change being backwards incompatible with v2), but due to this being a strictly free-time project, it might be few weeks before I have time to finish it.

> How save is to use version 3.0.0-preview4?

In what way? I know a bunch of places that use it, but there will be at least one more breaking change away from it.

> Do I have to expect breaking changes for release version 3.0.0?

Compared to v2? YES ABSOLUTELY

Compared to latest preview: Yes, if you use multi reporter support already.

**Comment by rabauke** [comment]
Thanks for this clarification, helps a lot.
