### ISSUE TITLE
3.0.1 installs empty directories include/catch2/benchmark/internal and include/catch2/generators/internal

### ISSUE THREAD

**Issue by yurivict** [catchorg/Catch2#2457]

**Comment by horenmar** [comment]
This seems to be down to https://github.com/catchorg/Catch2/blob/d32fca4a4949f8ce86da5d87f6d109ab21a88fa1/src/CMakeLists.txt#L355-L363 where CMake's `install(DIRECTORY` picks up directories that don't contain any copied files (notice the file pattern at the end).

I am not sure if this is the expected behaviour, or if CMake would be willing to change this. Either way I am willing to merge a CMake change that removes the empty dirs as a postprocessing step, but for me personally it is a very low priority change.

**Comment by ferdnyc** [comment]
@horenmar 
> I am not sure if this is the expected behaviour, or if CMake would be willing to change this.

It definitely is, and they're probably not. It is documented (after a fashion) in the `install(DIRECTORY...` docs.

It can be worked around, for this particular case, like so:
```cmake
    # Install the headers
    install(
      DIRECTORY
        "${SOURCES_DIR}"
        "${CMAKE_BINARY_DIR}/generated-includes/catch2" # Also install the generated header
      DESTINATION
        "${CMAKE_INSTALL_INCLUDEDIR}"
      FILES_MATCHING
        PATTERN "*.hpp"
      PATTERN "benchmark/internal" EXCLUDE
      PATTERN "generators/internal" EXCLUDE
    )
```
With a couple of caveats:
1. any other empty dirs would have to be explicitly added as well, obviously
2. slightly less obviously (at least, from a maintenance standpoint), if there ever _are_ any files added to either of those dirs that **should** be installed, they won't be until the `PATTERN ... EXCLUDE` is removed.
