### ISSUE TITLE
Build option BUILD_SHARED_LIBRARIES is not documented

### ISSUE THREAD

**Issue by HenryMiller1** [catchorg/Catch2#2497]
catch version 3 can build shared libraries, but this is not documented in configuration.md.  There are some comments on cmake about what you normally wouldn't want to do this (on windows), but for some it is the best choice and they won't always look in the cmake files to see hidden options.

**Comment by horenmar** [comment]
If you mean that we don't document that it exists, then yes, because [`BUILD_SHARED_LIBS` is a standard CMake option](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) and I generally don't want to duplicate CMake docs.

We admittedly also don't document the drawbacks and issues, which is something we should fix.
