### ISSUE TITLE
CHECK( array == another_array ) string expansion disagrees with comparison (Catch v2.13.10)

### ISSUE THREAD

**Issue by rimathia** [catchorg/Catch2#2598]
**Describe the bug**
```
CHECK( array == another_array )
```
 with array a C array of fixed size compares two pointers (the array addresses) but prints the arrays as containers when reporting the failure.

I understand (now) that this results in a comparison of two pointers. However, in this case the string that reports the test failure suggests that the content of the arrays should have been compared, which makes this a bit confusing.

**Expected behavior**
Either compare the arrays as ranges or print the arrays as pointers in the report

**Reproduction steps**
main.cpp:
```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

#include <type_traits>
 
TEST_CASE("two different arrays")
{
    int expected[] = {1, 2, 3};
    int observed[] = {1, 2, 3};
    static_assert(std::is_same_v<decltype(expected),int[3]>);
    CHECK( expected == observed );
}

```
clang++ main.cpp --std=c++17 && ./a.out 
output:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a.out is a Catch v2.13.10 host application.
Run with -? for options

-------------------------------------------------------------------------------
two different arrays
-------------------------------------------------------------------------------
main.cpp:7
...............................................................................

main.cpp:12: FAILED:
  CHECK( expected == observed )
with expansion:
  { 1, 2, 3 } == { 1, 2, 3 }

===============================================================================
test cases: 2 | 1 passed | 1 failed
assertions: 2 | 1 passed | 1 failed



**Platform information:**
 - clang++ --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix

**Comment by rimathia** [comment]
If this is actually considered a bug I'm happy to try whether I can fix it.

**Comment by horenmar** [comment]
It is not a bug as much as it is a design choice, that sometimes turns out unfortunate.

Catch2's stringification is never contextual, that is, when something is converted to string, it does not know in what context it will be used. This means that the same output will be used for `a` in 

```cpp
int a[2];
int b[2];
REQUIRE( a == b ); // compares pointers
```

and for `a` in

```cpp
int a[2];
REQUIRE_THAT(a, Contains(1)); // looks for 1 in the array
```

The current stringification for `T[sz]` is to treat it as a range, which is correct for the matcher assertion, but incorrect for the first case. Treating `T[sz]` as a pointer would be correct for the first case, but incorrect for the second one. We can pick only one of these, and what currently happens seemed like the better option at some point in the past 🤷

This does not mean it cannot change in the future, just that we can't make everyone happy, and I would have to see a lot of people preferring the stringification to happen the other way around.

**Comment by rimathia** [comment]
Thanks a lot for the very fast reply (and for your work on this extremely convenient tool in general). I half suspected that this isn't a bug as such but wanted to err on the side of reporting to make sure. By the way: using -std=c++20 the clang version I'm using already yells at me because of the array comparison (-Wdeprected-array-compare), so it certainly makes sense to prefer to get the right behaviour in the second case you mentioned.
