### ISSUE TITLE
Problems using `pkg-config` to correctly link `catch2` v3

### ISSUE THREAD

**Issue by fsandhei** [catchorg/Catch2#2695]
Hi,

I'm working on a project of mine that creates a meta build system for C++ (shamelessly linked [here](https://github.com/fredriksd/yambs)). In this project I try to steer away from CMake in linking dependencies and thus have tried to use `pkg-config`. On adding support for `pkg-config` I used Catch2 as an example input for my project.

First, I installed Catch2 with `vcpkg` with following version:
```
[fredrik@core ~/dev/github/vcpkg (master)✔]$ ./vcpkg --version
vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895

See LICENSE.txt for license information.
[fredrik@core ~/dev/github/vcpkg (master)✔]$ vcpkg list | grep catch2
catch2:x64-linux                                  3.3.2               A modern, header-only test framework for unit te...
```

Then I figured I'd try using a minimal example of Catch2 and compile using `pkg-config` to get link information:
#### Compiler version
```
[fredrik@core ~/dev/github/cpp/catch2-pkgconfig-test]$ g++ --version
g++ (GCC) 13.1.1 20230429
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
#### Test program
```
[fredrik@core ~/dev/github/cpp/catch2-pkgconfig-test]$ cat main.cpp
#include <catch2/catch_test_macros.hpp>

#include <cstdint>

uint32_t factorial( uint32_t number ) {
    return number <= 1 ? number : factorial(number-1) * number;
}

TEST_CASE( "Factorials are computed", "[factorial]" ) {
    REQUIRE( factorial( 1) == 1 );
    REQUIRE( factorial( 2) == 2 );
    REQUIRE( factorial( 3) == 6 );
    REQUIRE( factorial(10) == 3'628'800 );
}
```
#### Invocation
```
[fredrik@core ~/dev/github/cpp/catch2-pkgconfig-test]$ export PKG_CONFIG_PATH=$VCPKG_ROOT/installed/x64-linux/lib/pkgconfig
[fredrik@core ~/dev/github/cpp/catch2-pkgconfig-test]$ g++ -o x main.cpp $(pkg-config --libs --cflags catch2-with-main)
/usr/bin/ld: cannot find -lCatch2Main: No such file or directory
collect2: error: ld returned 1 exit status
```
As observed the linker cannot locate `libCatch2Main.a`. Similarly is the case using the debug version.

Using `pkg-config` through CMake works because CMake attempts to find the libraries' full paths instead of solely relying on the outpuf of `pkg-config`.

Have I mistaken something or is this a possible bug in the `pkg-config` file?

Thanks

**Comment by horenmar** [comment]
`vcpkg` drops `Catch2Main` into `lib/manual-link`, but does not adjust the pkg-config files appropriately.

**Comment by fsandhei** [comment]
So if I understand you correctly then it is a `vcpkg` issue? According to [this](https://github.com/microsoft/vcpkg/issues/14894) thread, I get the impression the `vcpkg` maintainers mean the *.pc files are not correctly written.

But from a user perspective: If you want to use `catch2` with `pkg-config`, how are you intended to do so then? Clone `catch2` and install the project manually?

Edit: After reading more about how the directory layout of `vcpkg` is, it seems to me that it is by intention placed in `manual-link` directory to deter automatic linkage, and thus it is up to the user themselves to manually link in `libCatch2Main.a`.

**Comment by horenmar** [comment]
Catch2 generates `.pc` files that work for the given build, if it is installed. From my PoV, this is where our responsibility ends. If some pkg manager (e.g. vcpkg) changes the installed folder structure, then they have the responsibility to also fix up the `.pc` files accordingly.

To the best of my knowledge, different package managers do not have this issue -- e.g. conan install afaik drops both libraries into `lib/`, so the `.pc` files we provide work. What needs to happen here is that vcpkg's port needs to fixup the paths manually -- you should open up an issue about this there.

> Edit: After reading more about how the directory layout of vcpkg is, it seems to me that it is by intention placed in manual-link directory to deter automatic linkage, and thus it is up to the user themselves to manually link in libCatch2Main.a.

Yes, but actually no.

`manual-link` exists due to vcpkg's support for global MSBuild integration, which works by changing some global config to point to vcpkg's installed packages. For libraries, this causes all libraries inside that specific folder to be automatically considered for linking... but doing this with libraries that contain `main` can break in various interesting ways, so vcpkg introduced `manual-link` subdirectory, where ports install libraries that contain `main`.

Portfiles are supposed to fix up non-msbuild helpers to ensure that they work even with the changed folder layout; you can see this if you use vcpkg-installed Catch2 through its CMake targets, as `Catch2WithMain` target properly links the main.

**Comment by fsandhei** [comment]
Thanks for your detailed response. I'm considering to attempt fix it and open a pull request to vcpkg on this.
