### ISSUE TITLE
builds, but No tests were found

### ISSUE THREAD

**Issue by opmtk** [catchorg/Catch2#2914]
**Describe the bug**

I started to write a simple test for my project, below of my top-level project. On the bottom of this top-level `CmakeLists.txt`, I  do:

```
make_minimum_required(VERSION 3.28)
project(cool_app)
...
# Unit tests
add_subdirectory(test)
```

The test sub-dir contains the CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.28)

set(PROJECT_UNIT_TESTS_NAME ${CMAKE_PROJECT_NAME}_unit_tests)
project(${PROJECT_UNIT_TESTS_NAME} LANGUAGES CXX VERSION 0.0.1)

find_package(Catch2 3 REQUIRED)

include(CTest)
include(Catch)

add_executable(${PROJECT_UNIT_TESTS_NAME} test1.cpp)
target_link_libraries(${PROJECT_UNIT_TESTS_NAME} PRIVATE Catch2::Catch2WithMain)

enable_testing()
catch_discover_tests(${PROJECT_UNIT_TESTS_NAME}
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/build
)
```

After successfully build I want to run it:

```
$ ctest --test-dir ./build
Internal ctest changing into directory: /home/${USERNAME}/work/my_project/build
Test project /home/${USERNAME}/work/my_project/build
No tests were found!!!
$ ls -la build/test/cool_app_unit_tests
-rwxrwxr-x 1 ${USERNAME} ${USERNAME} 1133056 Sep 27 20:10 build/test/cool_app_unit_tests*
```

So, it exist but isn't found finally.

**Expected behavior**

running the test

**Platform information:**

 - OS: **Ubuntu 24.04.1 LTS**
 - Compiler+version: **GCC 13**
 - Catch version: **3.4.0-1build1* (Ubuntu shipped)

**Additional context**

I've checked the docs and Stackoverflow without success.

**Comment by manuel-arguelles** [comment]
@opmtk I'm having the same issue, care to share how you solved it?

**Comment by opmtk** [comment]
I then gave up at some point and chose the pure/classic CMake way - at least that works as expected or described.

**Comment by freenull** [comment]
I've just wasted an hour on this error. I put `include(CTest)` and `enable_testing()` in the CMakeLists inside my test directory, and it turns out CTest sets its binary directory relative to the directory where you run this. My test source directory was `src/tests` and the binary directory was `build/src/tests`, and that is where the CTest config ended up. Running `ctest -T test` inside that directory worked.
I moved the include and `enable_testing()` to the top level CMake and now it works from the top level of the binary/build directory.

Edit:
[Serves me right](https://cmake.org/cmake/help/latest/command/enable_testing.html) :)
> This command should be in the top-level source directory because [ctest(1)](https://cmake.org/cmake/help/latest/manual/ctest.1.html#manual:ctest(1)) expects to find a test file in the top-level build directory.
