### ISSUE TITLE
Test case grouping

### ISSUE THREAD

**Issue by m-mcgowan** [catchorg/Catch2#320]
Unless I've missed it, it doesn't seem possible to group test cases into larger structures. 

With UnitTest++, you can group tests into suites:

``` cpp
  SUITE(MySuite)
  {
    TEST_CASE(...)
  }
```

It would be great to have this in Catch - it would make test organization possible (and simple). Nesting suites, or groups, would be a natural way to organize a large body of tests.

This would also make the junit reporter make more sense which presently creates a single `<testsuite>` element (with no name). With `SUITE()` support, it could output multiple suites, giving nicer organization in HTML test reports.

Sweet!

**Comment by philsquared** [comment]
This ticket is quite old - and seems at least partially addressed.
In addition to the suggestions I already made, you can also now run with `-#` to cause Catch to automatically tag every test case with a tag based on the filename (see: https://github.com/philsquared/Catch/blob/master/docs/test-cases-and-sections.md#special-tags)

Is anyone still dissatisfied with these options? (@m-mcgowan, @wichert)?

**Comment by tsondergaard** [comment]
The tagging mechanism is excellent for controlling which tests to run, but I am having problems creating adequately structured junit xml reports for display in Jenkins. The junit plugin in Jenkins is a little strange. It doesn't care about the <testsuite> hierarchy in the xml, instead it displays the test results in a hierarchy based on java-packages, which is forms by splitting the classname attribute of the <testcase> element by ".".

The Catch::JunitReporter would serve the needs of my project well if the classname attribute of the <testcase> element was formed using the <suite-name>.<[#filename]>.<testcasename>

We run the same test code compiled as 32-bit and 64-bit code and the with the <suite-name> included as above, it would be possible to run the test as "test-executable -n win32.x86 -# -r junit -o junit-report-x86.xml" and " test-executable -n win32.x64 -# -r junit -o junit-report-x64.xml" and get two xml reports that jenkins will group nicely by architecture (x86 and x64).

**Comment by horenmar** [comment]
I believe the last comment was addressed in the linked issue, so I am going to close this.

**Comment by LecrisUT** [comment]
If I may revive this issue, I would say tags are not groups, and the main advantage of grouping would be in displaying the reports, and finding the failing errors, while tags are meant for filtering. For example:

```cpp
Group(BackEnd){
  Group(Database){
    TEST_CASE(..., "[NeedsInternet, MySQL]")
  }
  Group(API){
    TEST_CASE(...)
  }
}
Group(FrontEnd){
  TEST_CASE(...)
}
```

On the backend it could be made that each top-level group is its own executable/cmake target, unless a custom implementation is requested.

---

#### Benefits

- More readable tests. I would like it that ctest and catch2 test executable display the results of these tests as a tree, i.e.:
  ```
  Backend: 58 Tests Enabled, 34 Tests Skipped
    |
    |-- Database: ...
    |
    |-- API: ...
  Frontend: ...
    |
  ```
- Instead of being bombarded with hundreds of TestCases, it would be clearer to expand the tree where the specific tests failed. That way the developer can navigate back to either or both the test source and main source to make necessary changes
- Simpler more descriptive test names
- Having each group as separate executable/cmake target, it is easier to enable building and conditionally linking the tests, e.g. depending on compiler or available libraries
