### ISSUE TITLE
ANSI colours even under Windows

### ISSUE THREAD

**Issue by vadz** [catchorg/Catch2#339]
It would be nice if the tests could show colours when running in a terminal emulator such as mintty. The existing POSIX colours code would work if only if were compiled in but currently it isn't.

So I'd like to suggest to build the POSIX implementation even under Windows, so that both are available and decide during run-time which one to use (it's possible to check if the program is running under a real console). Would a patch doing this be accepted?

P.S. Original proposal was to always use POSIX implementation under Windows but I was wrong, this doesn't really work.

**Comment by philsquared** [comment]
I'm doing a review of old issues.
I know there was an outstanding portion regarding runtime selection of Windows vs Posix colouring, but I'm not sure that's worth ever doing.
So I'm inclined to close this ticket now. Any objections?

**Comment by vadz** [comment]
Well, I'd still like to get nicely coloured output in MinTTY (Cygwin terminal emulator), but, obviously, this is not something really critical...

**Comment by philsquared** [comment]
But you can specify that at compile time

**Comment by vadz** [comment]
I never compile Cygwin (i.e. Unix/POSIX) applications, i.e. all my code is compiled as native Windows stuff, I just use Cygwin for convenience interactively. Not having colour when running in MinTTY is definitely a lesser problem than building a special version for Cygwin, I don't think anybody, let alone me, does or would even consider doing it...

**Comment by philsquared** [comment]
oic.
The trouble is that, although sending the control codes seems like a runtime selectable thing on Windows, there are additional calls around it that write POSIX headers to be available - so a vanilla windows build is not going to work.
It's possible things could be reworked to avoid that. Perhaps I'll look at that after all...

**Comment by Leandros** [comment]
Windows, in terms of terminal coloring, is rather difficult, compared to other *nix/bsd based operating systems, because you have multiple types of tty you need to support. There is cmd.exe, which is what we all know and love, but does not accept ANSI codes. And there is bash.exe (often bundled via Git or MinGW), which runs native win32 binaries (unlike cygwin), but accepts ANSI color codes.

**Comment by Leandros** [comment]
Windows, in terms of terminal coloring, is rather difficult, compared to other *nix/bsd based operating systems, because you have multiple types of tty you need to support. There is cmd.exe, which is what we all know and love, but does not accept ANSI codes. And there is bash.exe (often bundled via Git or MinGW), which runs native win32 binaries (unlike cygwin), but accepts ANSI color codes.

I've met this problem a number of times in different applications already, and in my opinion, the best way is to support both. This can be achieved by building a small abstraction on top of the color output, which will either select based on the operating system whether to use bash or you're running on windows. On windows you need to detect whether your output is going to cmd.exe or to bash.exe (which is not exactly obvious how to achieve, but you can [refer to my blog post here](https://arvid.io/2017/04/23/is-my-process-running-from-bash-exe-or-cmd-exe/) about how to achieve it) and based on that pick the coloring mechanism.

**Comment by philsquared** [comment]
Thanks Leandros,

We have most of that already (the abstraction for the colourising mechanism). Currently for Windows it only uses the win32 calls. I'll check your blog post at some point (snowed under now) for how to handle the last part - thanks.

**Comment by Leandros** [comment]
Awesome! Sounds great!

**Comment by jamespharvey20** [comment]
I can't get colorized output on Windows running `ctest` through a command window.  I know nothing about Windows command line color, other than it's not ANSI.  Since `ctest` is buffering the output, I think, is it just impossible to use color through it?

Likewise, I also can't get colorized output on Windows running in a VS CMake window (CMake->Run All Tests) which invokes `ctest`.  I know even less about if it's even possible to use color here, since ctest is not only buffering it, but VS winds up displaying it.  Perhaps the only way is to use the VSColorOutput extension.

In my `CMakeLists.txt`, I have `add_test(unitTestX unitTestX --use-colour yes)` and I've also put `#define CATCH_CONFIG_COLOUR_WINDOWS` in the cpp file with `#define CATCH_CONFIG_MAIN`.  (This is all before the `#include "catch.h"`.)

The `CATCH_CONFIG_COLOUR_WINDOWS` does have the effect of when the unitTest is being ran directly, it uses color, without having to specify a command line argument.

The `add_test(... --use-colour yes)` seems to have no effect on Windows.  (It does on linux.)  When I run `ctest`, in a command window, it still prints in black and white.

**Comment by Leandros** [comment]
Since the output is piped through Ctest, it'll swallow all colors. Win32, in comparison to Linux, doesn't use escape code, but requires to modify the underlying console, which will obviously be swallowed by ctest. Unless colors are added to ctest itself, you're out of luck.
What you could try is to run ctest in a git bash (https://git-scm.com) and configure catch to use ANSI escapes.
