### ISSUE TITLE
Skipping tests

### ISSUE THREAD

**Issue by ibell** [catchorg/Catch2#355]
It would be really nice if there was a facility to skip tests.  

My use case is this: Library A should test its interaction with Library B, but only if Library B is installed.  Otherwise, it should skip the Library B interaction tests and inform the user that Library B could not be found.  Of course, this could be thrown as an error, but there are many use cases where skipping the impossible tests and making a note of them is useful.

**Comment by hauke76** [comment]
Hi, I am curious whether it is also possible to skip tests at run-time.

Assume I had a unit test which requires a specific OpenGL version not present on the test machine where the test is currently run. It would be great to be able to skip such a test if I determine at run-time that I cannot reasonably perform it. As of today, I can skip but not invoking the respective assertion macro but I cannot log or report that I skipped a test. I looked at the code and tried to find out whether I could e.g. adapt the return value of a user specified main() but the return value of Session::run() seems to be already used otherwise.
