### ISSUE TITLE
Cleaning up catch memory after running tests

### ISSUE THREAD

**Issue by Hedanito** [catchorg/Catch2#494]
I've made my own memory tracer by overloading new and delete. I want to use it during tests so I made my own main function and called Catch from there. It looks something like this:

```
MemoryManager memorymanager;
memorymanager.RegisterSingleton();

int result = Catch::Session().run();

auto allocations = memorymanager.GetAllocations();
```

Now the problem here is that Catch seems to leak 1 or 2 allocations (not always the same, so hard to predict as well), which prevents me from tracing memory leaks accurately. I assume they are from singletons and are cleaned up once the program shuts down, but that is too late for me.

I tried running Catch once with no tests before I start tracing so that those allocations aren't traced, but it turns out Catch can't run more than once in a single session.

So I am pretty much out of ideas. How do I either clean up catch before the end of the program, or accurately ignore the allocations made by Catch?

**Comment by Manuzor** [comment]
Just a shot in the dark but have you tried something like this:

```cpp
// Create session, which may allocate stuff.
Catch::Session session;

// Create memory manager, which will start tracking leaks from this point on.
MemoryManager memorymanager;

// Run the tests. It hopefully does not allocate stuff that the session cleans up.
int result = session.run();

// Now check for leaks.
auto allocations = memorymanager.GetAllocations();
```

**Comment by philsquared** [comment]
Sorry for the delay in getting to this.
Could I ask what platform you're using (OS and compiler)?
The main reason for the Session class is precisely to make sure that all singleton data is cleaned up deterministically so that leak detection is not impacted. I regularly use it in a large VC++ code-base with dbghelp leak detection.
Also if you have any information about where the leaks are coming from in your case that would help too.

**Comment by Hedanito** [comment]
I am using VS2015.

I did some more searching, and the issue seems to be the TagAliasRegistry singleton.
The instantiation of this singleton calls `new` somewhere and allocate 92 bytes.
However, `delete` doesn't seem to be called for this memory (at least before the program teminates).

I'm also pretty sure that I've overloaded all the new/delete functions, but here are the signatures just to be sure:
    void* operator new (std::size_t a_Size);
    void* operator new (std::size_t a_Size, const std::nothrow_t&) noexcept;
    void* operator new[] (std::size_t a_Size);
    void* operator new[] (std::size_t a_Size, const std::nothrow_t&) noexcept;

    void operator delete (void *a_Memory) noexcept;
    void operator delete (void *a_Memory, const std::nothrow_t&) noexcept;
    void operator delete[] (void *a_Memory) noexcept;
    void operator delete[] (void *a_Memory, const std::nothrow_t&) noexcept;

**Comment by Hedanito** [comment]
Using some brute force:

    auto& registry = Catch::TagAliasRegistry::get();
    registry.~TagAliasRegistry();

Doing this will result in `delete` being called on the leaked memory, so I am pretty certain this one is the issue.

**Comment by philsquared** [comment]
Thanks. Odd that that doesn't show up in my own leak detection.
I'll look at getting that added to the clean-up.

**Comment by d-led** [comment]
I've stumbled upon two indicators that there are memory leaks. One: used a scoped `mtrace` on linux, and get an yet unidentified leak by simply asserting something using `REQUIRE`.

Another possible leak is detected using [CodeChecker](https://github.com/Ericsson/codechecker) (based on clang tools):
![catch_mem_leak1](https://cloud.githubusercontent.com/assets/1716584/22371838/d34e27f0-e499-11e6-801e-680c500c2e09.png)

The latter is probably unrelated to the former, but I haven't yet dug into the issue.

**Comment by horenmar** [comment]
@d-led The second is a false positive -- `registerTestCase` creates `TestCase` object that takes ownership of the allocated object.

The first one is interesting, because both ASAN and Valgrind are ok with the current master. Does it trigger for you with any single `REQUIRE`?

**Comment by d-led** [comment]
@horenmar perhaps, if the `MethodTestCase` constructor never throws.

As for `REQUIRE`, I will try to build a minimal example to reproduce it when I get a bit of free time. Those that triggered were in the form `REQUIRE(true)`.

**Comment by d-led** [comment]
@horenmar couldn't reproduce in a self-contained simple example using [tracey](https://github.com/r-lyeh/tracey) (no leaks after all tests have run). I suppose, it might be legitimate that memory locally grows after one assertion, but will be freed upon finishing the test run.

**Comment by horenmar** [comment]
Since it seems that it was a false positive, with Valgrind, ASan and Windows crtdbg coming up clean, I am going to close this soon.

**Comment by philsquared** [comment]
The original issue was regarding the `TagAliasRegistry` which, for some reason, was operating as it's own singleton (using a method-scoped static - so not participating in early clean-up).
I've changed this now to be managed by the `RegistryHub`, which is cleaned up eagerly at the end of the `Session` instance, so I'm confident that addresses @Hedanito's original issue (sorry it took so long to get back to this).

As for the additional "leaks" that @d-led raised I'm inclined to agree with @horenmar that these are false positives (I vaguely remember possibly discussing this in Munich, @d-led?).

I suspect that what is being flagged is that an object is created with new as part of the parameter initialisation which, while it will have ownership taken within the function, would leak if the evaluation of one of the other arguments throws. In practise this is not an issue, but it would be nice if we could silence all analyser warnings. This is not as straightforward as it might be because I don't want to add too much extra machinery at this point as it's compiled into every test case - but will see what I can do.

However I think we can probably close this issue in view of the `TagAliasRegistry` changes - at least once it makes it into the single include - unless anyone has any objections?

**Comment by d-led** [comment]
@philsquared yep. Agree. No action needed, I think.
P.S. I guess we did briefly talk about it Munich 😄

**Comment by lightmare** [comment]
> I suspect that what is being flagged is that an object is created with new as part of the parameter initialisation which, while it will have ownership taken within the function, would leak if the evaluation of one of the other arguments throws. In practise this is not an issue, but it would be nice if we could silence all analyser warnings. This is not as straightforward as it might be because I don't want to add too much extra machinery at this point as it's compiled into every test case - but will see what I can do.

You already have these ref-counted, so it'd follow to do the allocations with something the likes of `make_shared`, returning a `Ptr` right away, instead of passing a raw pointer down to where it finally gets wrapped in a `Ptr`. Granted you don't have perfect forwarding, but 3 short templates for taking up to 2 arguments by reference would suffice for most uses within Catch.
