### ISSUE TITLE
Is there any mock framework working with catch.hpp?

### ISSUE THREAD

**Issue by newread** [catchorg/Catch2#55]
Is there any more complicated sample for tdd development?

thanks

**Comment by ppatoria** [comment]
I just gone through some of your videos and  like catch2 very much but without mocj we can't do serious testing  and I think ad-hock mocks or stub is very time consuming and doesn't have capability to verify if a method is called (i.e . how many times it is called, with specific parameter value ... etc) . So I think catch2 should support some mock framework without that its not complete.

Google mock is ugly and need lot of code , a better framework is required something similar to mock frameworks available in .Net and Java. 

Also just want to what's your opinion on design by contract ? Which is more natural way of writing safe code. A combination of design by contacts and unit tests seems to me a better approach.

**Comment by dvirtz** [comment]
I've been successfully using FakeIt:
https://github.com/eranpeer/FakeIt

**Comment by TrueWodzu** [comment]
> 
> I've been successfully using FakeIt: https://github.com/eranpeer/FakeIt

Thank you, it looks great.

**Comment by osmeest** [comment]
Tried out FakeIt a little. Deception around the corner: in the verification phase (after the calls), it cannot properly match method calls with argument matching when the methods take their arguments as reference (eg. to temporary).
Such a pity because it looks nice and integrates nicely with multiple testing frameworks (like catch2).
Any other suggestion ?

**Comment by matepek** [comment]
This is might interesting for someone: https://github.com/matepek/catch2-with-gmock

**Comment by FranckRJ** [comment]
@osmeest 

> Tried out FakeIt a little. Deception around the corner: in the verification phase (after the calls), it cannot properly match method calls with argument matching when the methods take their arguments as reference (eg. to temporary). See issue 108.
> Such a pity because it looks nice and integrates nicely with multiple testing frameworks (like catch2).
> Any other suggestion ?

FakeIt, but instead of using Verify to check if a method was called with a given argument, mock this method only for the argument you want.

In brief, don't do this after the calling the thing you want to test : 

```cpp
Verify(Method(mock, foo).Using(str));
```

But do this before calling the thing you want to test : 

```cpp
When(Method(mock, foo).Using(str)).Return();
```

It does almost exactly the same.
