### ISSUE TITLE
cppcheck: "failed to expand 'SECTION', Wrong number of parameters for macro 'SECTION'."

### ISSUE THREAD

**Issue by ibc** [catchorg/Catch2#868]
* Catch version: **v1.8.1**
* Operating System: **OSX Sierra**
* Compiler+version: **clang Apple LLVM version 8.0.0 (clang-800.0.42.1)**

Using `SECTION("foo")` makes Codacy's cppcheck [unhappy](https://www.codacy.com/app/ibc/mediasoup/issues?bid=4224311&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvciBQcm9uZSJdfV0=):

```
failed to expand 'SECTION', Wrong number of parameters for macro 'SECTION'.
```

I understand the issue happens due this macro:

https://github.com/philsquared/Catch/blob/master/include/catch.hpp#L216

However, the [doc](https://github.com/philsquared/Catch/blob/master/docs/test-cases-and-sections.md#test-cases-and-sections) says nothing about `SECTION(name, description)` but just about `SECTION(name)`.

Missing stuff in the doc?

**Comment by grahamshanks** [comment]
I believe that the documentation is lagging behind the code.

There is a wider problem though. For "modern" compilers (i.e. those with variadic macro parameters) you can write either `SECTION("foo")` or `SECTION("foo", "description")`. However the remaining compilers require both parameters. In our case we have to support legacy compilers so our code need to explicitly include a description (which we usually just set to the empty string) so that our units tests are portable between all our compilers. It is far too easy to forget to add the description when working on a computer without a legacy compiler installed and it only gets noticed when the build bot fails.

It would be nice to have separate macros for SECTIONs with and without a description for older compilers and, using a compiler flag, exclude the standard SECTION variadic macro so that all compilers would give a compilation failure if the right number of parameters were not given to SECTION.

**Comment by Wingsofcourage** [comment]
Any news here ?

**Comment by horenmar** [comment]
This ~is~ was an artefact of development. `SECTION`s used to have name + description, but with variadic macros allowing for just one of these, the two argument version quickly stopped being used anymore, as the single argument version offered better UX. The not-so-good side effect was that the most common way to write `SECTION`s was not compatible with old compilers.


Anyway, the current version no longer supports compilers without support for variadic macros and the v1 line of versions is no longer under active development. If you are stuck with the old versions, the best thing you can do is to just quickly cut down the non-variadic version to use only a single argument.
