### ISSUE TITLE
const std::string & instead of const char[]

### ISSUE THREAD

**Issue by palindromoroz** [catchorg/Catch2#906]
TEST_CASE and other statements (not sure if all) require const char[]. Using const std::string & would make it much easier and more flexible for users. Or maybe I oversee something here?

**Comment by philsquared** [comment]
The original reason was that when I made those `std::string`s it dramatically increased build times (at least on the platform I was testing it on at the time). Since then I suspect that the effect, if still there, is dwarfed by other areas (although we're trying to fix that).
In practice these would be better served by something like `std::string_view`, but for Catch2 I'm planning to roll out my own StringRef (which is similar) and will use that.

**Comment by palindromoroz** [comment]
One reason I tried Catch is because of the hierarchy. I want many tests across different parts of the parameter space so I generate many sections. Than it is handy to generate section names in some easy fashion as I do not hard-code them.

**Comment by philsquared** [comment]
Sorry I didn't respond back sooner - this one got lost (I think while I was at C++Now!).

`SECTION`s do, in fact, take their string arguments as `std::string`s - for precisely the reason your say - so you can dynamically building them.
